"""Haven 1.2 interaction tests. --isolated uses an in-memory storage adapter.
The isolated environment verifies DOM interactions, not native browser persistence.
Live OpenAI responses are NOT exercised by this suite (see ai.test.mjs for mocked contracts).
"""
from pathlib import Path
import argparse, json, shutil
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--isolated',action='store_true');parser.add_argument('--url',default='http://localhost:3000/dist/index.html');args=parser.parse_args()
HTML=(ROOT/'dist/index.html').read_text();checks=[];errors=[]
STORAGE="""() => {const v=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>v.get(k)??null,setItem:(k,x)=>v.set(k,String(x)),removeItem:k=>v.delete(k),clear:()=>v.clear()}})}"""
def check(name,value):
    checks.append({'name':name,'passed':bool(value)})
    assert value,name
    print('PASS',name)
def load(page):
    if args.isolated:page.evaluate(STORAGE);page.set_content(HTML,wait_until='load')
    else:page.goto(args.url)
    page.locator('main').wait_for()
def nav(page,name):
    if page.viewport_size['width']<=780:page.locator('[data-action="menu"]').click()
    page.locator(f'.nav-item[data-page="{name}"]').click()
def send(page,text):
    page.locator('#assistant-input').fill(text);page.locator('#assistant-send').click()
    page.wait_for_function("document.querySelector('#assistant-working').hidden")
    return page.locator('.from-haven').last.inner_text()
def reset(page):page.locator('.assistant-reset').click()
def latest_cards(page):return page.locator('.from-haven').last.locator('.assistant-property')
def no_overflow(page):return page.evaluate('document.documentElement.scrollWidth <= innerWidth')

with sync_playwright() as pw:
    browser=pw.chromium.launch(**({'executable_path':shutil.which('chromium') or shutil.which('google-chrome')} if shutil.which('chromium') or shutil.which('google-chrome') else {}),args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce',accept_downloads=True)
    page=context.new_page();page.set_default_timeout(5000);page.on('pageerror',lambda e:errors.append(str(e)))
    try:
        load(page)
        check('Assistant launches without changing the catalogue',page.locator('#stat-properties').inner_text()=='60')
        for target in ['saved','compare','calculator','custom','discover']:
            nav(page,target);check(f'Widget is present on {target}',page.locator('#assistant-launcher').is_visible())
        page.locator('#assistant-launcher').click()
        check('Panel exposes non-modal dialog semantics',page.locator('#haven-assistant').get_attribute('aria-modal')=='false')
        check('Opening widget focuses the message field',page.locator('#assistant-input').evaluate('(el)=>el===document.activeElement'))
        check('Launch button announces expansion',page.locator('#assistant-launcher').get_attribute('aria-expanded')=='true')
        check('Local mode and fictional data are visible',page.locator('#assistant-mode-text').inner_text()=='Local demo' and 'fictional' in page.locator('#assistant-messages').inner_text())
        check('Empty messages cannot be sent',page.locator('#assistant-send').is_disabled())
        page.locator('.assistant-info-toggle').click()
        check('Disclosure does not pretend a live model is connected','rule-based' in page.locator('#assistant-info').inner_text())
        page.locator('.assistant-info-toggle').click()
        page.locator('#assistant-input').focus();page.keyboard.press('Escape')
        check('Escape closes widget and restores launcher focus',not page.locator('#haven-assistant').is_visible() and page.locator('#assistant-launcher').evaluate('(el)=>el===document.activeElement'))
        page.locator('#assistant-launcher').click()
        response=send(page,'Chicago')
        check('City alone returns Chicago homes without a budget gate',latest_cards(page).count()==3 and 'Chicago' in response)
        response=send(page,'$600k')
        check('Budget refines results without a property-type gate',latest_cards(page).count()==3 and '$600,000' in response)
        response=send(page,'Any property type')
        check('Any property type preserves immediate recommendations',latest_cards(page).count()==3)
        response=send(page,'No must-haves')
        check('Conversation recommends exactly three matching Chicago homes',latest_cards(page).count()==3 and latest_cards(page).locator('.assistant-card-location').evaluate_all("nodes=>nodes.every(n=>n.textContent==='Chicago, IL')"))
        check('Recommendation explanations contain the actual price and $600,000 cap','$318,000' in latest_cards(page).first.inner_text() and '$600,000' in latest_cards(page).first.inner_text())
        check('Each card has working detail, calculator and save controls',latest_cards(page).first.locator('[data-chat-details]').count()==2 and latest_cards(page).first.locator('[data-chat-analyze]').count()==1 and latest_cards(page).first.locator('[data-chat-save]').count()==1)
        page.locator('.assistant-brief summary').click()
        check('Search recap exposes recognized criteria','Chicago' in page.locator('#assistant-preferences').inner_text() and '$600,000' in page.locator('#assistant-preferences').inner_text())
        page.locator('.assistant-brief summary').click()
        first=latest_cards(page).first
        first.locator('[data-chat-save]').click()
        check('Saving from chat updates its button and the workspace',first.locator('[data-chat-save]').get_attribute('aria-pressed')=='true' and page.locator('.nav-count[data-count="saved"]').inner_text()=='1')
        transcript=page.locator('#assistant-messages').inner_text()
        nav(page,'saved')
        check('Chat stays open across page navigation',page.locator('#haven-assistant').is_visible())
        check('Conversation survives shell re-rendering',page.locator('#assistant-messages').inner_text()==transcript)
        check('Chat-saved home is in Saved homes',page.locator('.property-card[data-property="sample-13"]').count()==1)
        latest_cards(page).first.locator('.assistant-property-title').click()
        check('View home opens the correct existing property',page.locator('#dialog-title').inner_text()=='The Wren Flat')
        page.locator('[data-action="close-dialog"]').first.click()
        check('Chat is available again after closing property details',page.locator('#haven-assistant').is_visible())
        latest_cards(page).first.locator('[data-chat-analyze]').click()
        check('Run numbers opens the correct calculator property','The Wren Flat' in page.locator('#calculator-property').input_value())
        check('Run numbers loads the matching price',page.locator('#calc-price').input_value()=='318000')
        check('Run numbers closes panel without erasing its conversation',not page.locator('#haven-assistant').is_visible())
        page.locator('#assistant-launcher').click()
        check('Reopened widget remembers the conversation',page.locator('#assistant-messages').inner_text()==transcript)
        reset(page)
        check('New chat clears the previous conversation',page.locator('.from-user').count()==0 and page.locator('.assistant-property').count()==0)
        send(page,'Lincoln or Omaha, under $400k. A house with at least 3 bedrooms and outdoor space.')
        check('Complete natural-language starter immediately recommends three homes',latest_cards(page).count()==3)
        ids1=latest_cards(page).evaluate_all('els=>els.map(e=>e.dataset.recommendation)')
        response=send(page,'Show me more matches')
        ids2=latest_cards(page).evaluate_all('els=>els.map(e=>e.dataset.recommendation)')
        check('Show more reveals the remaining matches without duplicates',len(ids2)==2 and not set(ids1)&set(ids2))
        response=send(page,'Actually make my purchase budget $300k')
        check('Follow-up changes budget and preserves location/type',latest_cards(page).count()==2 and 'Omaha' in latest_cards(page).first.inner_text())
        response=send(page,'Austin instead')
        check('No-match explanation does not silently widen constraints',latest_cards(page).count()==0 and 'haven’t stretched' in response)
        response=send(page,'San Francisco instead')
        check('Unsupported city is disclosed','San Francisco isn' in response and latest_cards(page).count()==0)
        reset(page)
        response=send(page,'Lincoln, house under $400k with a pool and 3 bedrooms')
        check('Unknown amenity never becomes a confirmed match',latest_cards(page).count()==3 and latest_cards(page).locator('.assistant-caveat').count()==3 and 'not fully verified' in response)
        response=send(page,"I don't need a pool")
        check('Removing an unverified requirement clears caveats',latest_cards(page).locator('.assistant-caveat').count()==0)
        response=send(page,'<img src=x onerror="window.havenInjected=true">')
        check('User text is escaped, not executed',page.evaluate('window.havenInjected !== true') and page.locator('.from-user').last.locator('img').count()==0)
        page.locator('#assistant-input').fill('Draft stays here')
        page.locator('#assistant-input').dispatch_event('keydown',{'key':'Enter','isComposing':True})
        check('IME composition Enter does not send early',page.locator('#assistant-input').input_value()=='Draft stays here')
        page.locator('#assistant-input').press('Shift+Enter')
        check('Shift+Enter inserts a newline', '\n' in page.locator('#assistant-input').input_value())
        page.locator('.assistant-close').click();page.locator('#assistant-launcher').click()
        check('Unsent text survives closing and reopening',page.locator('#assistant-input').input_value().startswith('Draft stays here'))
        reset(page);send(page,'Lincoln or Omaha, under $400k. A house with at least 3 bedrooms and outdoor space.');page.screenshot(path=str(ROOT/'docs/assistant-matches.png'))
        page.locator('.assistant-close').click();nav(page,'calculator')
        picker=page.locator('#calculator-property');label=picker.input_value()
        check('Calculator picker uses a combobox rather than native select',picker.get_attribute('role')=='combobox' and page.locator('select#calculator-property').count()==0)
        picker.click()
        check('Opening calculator menu offers all sixty homes',page.locator('[role="option"]').count()==60)
        check('Current selection is identified',page.locator('[role="option"][aria-selected="true"]').count()==1)
        picker.fill('')
        for text in ['C','Ch','Chi','Chic','Chica','Chicag','Chicago']:
            picker.fill(text)
            check(f'Live property suggestions update for {text!r}',page.locator('[role="option"]').count()>0 and picker.input_value()==text)
        check('Full city search has only Chicago homes',page.locator('[role="option"]').count()==3)
        check('Search suggestions include thumbnail, price, type and size',page.locator('[role="option"]').first.locator('img').count()==1 and '$318,000' in page.locator('[role="option"]').first.inner_text() and '1,210 sq ft' in page.locator('[role="option"]').first.inner_text())
        check('Typing does not change the selected scenario',page.locator('#calc-price').input_value()=='318000')
        page.screenshot(path=str(ROOT/'docs/calculator-search.png'))
        picker.press('ArrowDown');active=picker.get_attribute('aria-activedescendant')
        check('Arrow keys maintain an active descendant',active is not None and page.locator('#'+active).count()==1)
        picker.press('Enter')
        check('Enter chooses the highlighted listing',page.locator('#calc-price').input_value()=='465000' and 'Hawthorne Row' in page.locator('#calculator-property').input_value())
        check('After selection the popup is closed and focus stays in input',not page.locator('.picker-popup').is_visible() and page.locator('#calculator-property').evaluate('(el)=>el===document.activeElement'))
        picker=page.locator('#calculator-property');selected=picker.input_value();picker.fill('zzzznoresults')
        check('No-result search has a useful empty state',page.locator('.picker-empty').is_visible() and page.locator('[role="option"]').count()==0)
        picker.press('Enter')
        check('Enter cannot select a nonexistent property',page.locator('#calc-price').input_value()=='465000')
        picker.press('Escape')
        check('Escape restores selected property without changing calculator inputs',picker.input_value()==selected and not page.locator('.picker-popup').is_visible())
        picker.click();page.locator('.picker-clear').click()
        check('Clear search returns all homes without unselecting the scenario',picker.input_value()=='' and page.locator('[role="option"]').count()==60 and page.locator('#calc-price').input_value()=='465000')
        picker.fill('austin condo')
        check('Mixed city and type search resolves the right listing',page.locator('[role="option"]').count()==1 and 'The Terra Flat' in page.locator('[role="option"]').inner_text())
        page.locator('[role="option"]').click()
        check('Mouse choice loads corresponding inputs',page.locator('#calc-price').input_value()=='329000')
        picker=page.locator('#calculator-property');selected=picker.input_value();picker.fill('Lincoln');page.locator('h1').click()
        check('Clicking outside restores the actual selection',picker.input_value()==selected and not page.locator('.picker-popup').is_visible())
        picker.click();picker.press('Tab')
        check('Tab dismisses menu without accepting a suggestion',not page.locator('.picker-popup').is_visible() and page.locator('#calc-price').input_value()=='329000')
        # Add a custom entry, verifying picker integration without changing the assistant corpus.
        page.locator('[data-action="add-property"]').click()
        page.locator('#property-form input[name="name"]').fill('My Lighthouse')
        page.locator('#property-form input[name="address"]').fill('123 Test Lane')
        page.locator('#property-form input[name="city"]').fill('Test City')
        page.locator('#property-form input[name="state"]').fill('NE')
        page.locator('#property-form button[type="submit"]').click()
        nav(page,'calculator');page.locator('#calculator-property').fill('lighthouse')
        check('Calculator search includes user-added properties',page.locator('[role="option"]').count()==1 and 'My Lighthouse' in page.locator('[role="option"]').inner_text())
        page.locator('[role="option"]').click()
        check('Custom property can be selected for analysis','My Lighthouse' in page.locator('#calculator-property').input_value())
        page.locator('#assistant-launcher').click();reset(page)
        check('Assistant still labels its source as the 60 demo homes','60 fictional homes' in page.locator('#assistant-messages').inner_text())
        send(page,'Test City under $500k, any property type, no must-haves')
        check('Assistant never recommends a custom property as a demo fixture',latest_cards(page).count()==0)
        page.locator('.assistant-close').click()
        check('Desktop has no horizontal overflow',no_overflow(page))
        mobile=context.new_page()
        mobile.set_viewport_size({'width':390,'height':844});mobile.on('pageerror',lambda e:errors.append(str(e)));load(mobile)
        mobile.locator('#assistant-launcher').click()
        box=mobile.locator('#haven-assistant').bounding_box()
        check('Mobile widget stays inside the viewport',box['x']>=0 and box['y']>=0 and box['x']+box['width']<=390 and box['y']+box['height']<=844)
        check('Mobile chat does not introduce horizontal overflow',no_overflow(mobile))
        mobile.locator('[data-chat-suggestion]').first.click();mobile.wait_for_selector('.assistant-property');mobile.screenshot(path=str(ROOT/'docs/assistant-mobile.png'))
        latest_cards(mobile).first.locator('[data-chat-save]').click()
        check('Saving a recommendation works on mobile',latest_cards(mobile).first.locator('[data-chat-save]').get_attribute('aria-pressed')=='true')
        mobile.set_viewport_size({'width':390,'height':540})
        box=mobile.locator('#assistant-form').bounding_box()
        check('Composer stays visible with a shorter mobile viewport',box['y']>=0 and box['y']+box['height']<=540)
        mobile.set_viewport_size({'width':390,'height':844});mobile.locator('.assistant-close').click();nav(mobile,'calculator');mobile.locator('#calculator-property').fill('Seattle')
        box=mobile.locator('.picker-popup').bounding_box()
        check('Mobile autocomplete menu fits the screen',box['x']>=0 and box['x']+box['width']<=390 and box['width']>=300 and no_overflow(mobile))
        check('Mobile calculator search has enough space to type',mobile.locator('.picker-input-wrap').bounding_box()['width']>=240)
        mobile.screenshot(path=str(ROOT/'docs/calculator-search-mobile.png'))
        mobile.locator('[role="option"]').nth(1).click()
        check('Touch-style option selection loads the chosen property','Cloudline Apartment' in mobile.locator('#calculator-property').input_value())
        check('Reduced motion disables new widget and dropdown animations',mobile.locator('.picker-popup').evaluate("el=>getComputedStyle(el).animationName==='none'"))
        normal=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='no-preference');motion=normal.new_page();load(motion);motion.locator('#assistant-launcher').click()
        check('Motion-enabled widget has a finite entrance',motion.locator('#haven-assistant').evaluate("el=>getComputedStyle(el).animationIterationCount==='1'"))
        motion.locator('.assistant-close').click();motion.close();normal.close()
        check('No uncaught JavaScript errors in the entire suite',not errors)
        print(f'PASS: {len(checks)} assistant/picker browser checks. Isolated: {args.isolated}.')
    except Exception:
        page.screenshot(path=str(ROOT/'docs/assistant-test-failure.png'))
        raise
    finally:
        (ROOT/'docs/assistant-browser-results.json').write_text(json.dumps({'isolated':args.isolated,'checks':checks,'pageErrors':errors},indent=2))
        browser.close()
