import test from 'node:test';
import assert from 'node:assert/strict';
import {
  calculate, defaultAssumptions, defaultCalculatorAssumptions, withOwnershipCosts,
  cloneAssumptions, validateAssumptions, validateOwnershipCosts, changeCostBasis,
  resolvedOwnershipCosts, amortization
} from '../build/finance.js';
import { seedProperties } from '../build/data.js';
import { freshWorkspace, freshCalculator, parseWorkspace, parseCalculator, saveWorkspace, loadWorkspace, STORAGE_KEY } from '../build/storage.js';
import { modelAssumptionsRows } from '../build/views.js';
import { costHints, preciseMoney } from '../build/cost-controls.js';

const near=(actual,expected,epsilon=1e-7)=>assert.ok(Math.abs(actual-expected)<epsilon,`${actual} != ${expected}`);
const legacy=()=>({price:120000,downPercent:25,interestRate:0,years:15,rent:2000,taxAnnual:1200,insuranceMonthly:50,hoaMonthly:100,vacancyPercent:10,maintenancePercent:5,managementPercent:10,capexPercent:3,closingPercent:3,initialRepairs:10000,mortgageInsuranceMonthly:0});
const modern=()=>withOwnershipCosts(legacy());
const patch=(input)=>{const a=modern();Object.assign(a.costs,input);return a;};
const encode=JSON.stringify;

// Defaults / compatibility. The old calculate entry point is still authoritative.
test('cost controls: all sixty fixtures have finite valid independently editable defaults',()=>{
  for(const p of seedProperties){const a=defaultCalculatorAssumptions(p);assert.deepEqual(validateAssumptions(a),[]);assert.ok(Object.values(calculate(a)).every(x=>x===null||Number.isFinite(x)));assert.equal(a.costs.insuranceAnnual,p.insuranceMonthly*12);assert.equal(a.costs.hoaApplicable,p.hoaMonthly>0);}
});
test('cost controls: initial tax rate is the disclosed rounded fixture-derived rate',()=>{const p=seedProperties[0],a=defaultCalculatorAssumptions(p);assert.equal(a.costs.taxRatePercent,1.477);near(calculate(a).tax,400.0208333333333);});
test('cost controls: default monthly reserve carries forward the existing allowance',()=>{for(const p of seedProperties){const a=defaultCalculatorAssumptions(p);assert.equal(a.costs.maintenanceBasis,'monthly');near(a.costs.maintenanceValue,p.rent*.05);}});
test('cost controls: converting a legacy scenario preserves every original result',()=>{for(const p of seedProperties){const a=defaultAssumptions(p),old=calculate(a),converted=calculate(withOwnershipCosts(a));for(const key of Object.keys(old)){if(old[key]===null)assert.equal(converted[key],null);else near(converted[key],old[key],1e-6);}}});
test('cost controls: conversion never modifies the saved legacy source object',()=>{const a=legacy(),copy=encode(a),b=withOwnershipCosts(a);assert.equal(encode(a),copy);assert.equal(a.costs,undefined);assert.equal(b.costs.maintenanceValue,100);});
test('cost controls: repeated conversion preserves user values and selected units',()=>{const a=patch({maintenanceBasis:'home-value',maintenanceValue:1.2,closingBasis:'amount',closingValue:5250});assert.deepEqual(withOwnershipCosts(a),a);assert.notEqual(withOwnershipCosts(a).costs,a.costs);});
test('cost controls: unextended legacy assumptions keep rent-based maintenance',()=>{const a=legacy();near(calculate({...a,rent:3000}).maintenance,150);near(calculate(a).cashflow,710);});
test('cost controls: deep clone isolates the nested snapshot',()=>{const a=modern(),snapshot=cloneAssumptions(a);a.costs.maintenanceValue=900;assert.equal(snapshot.costs.maintenanceValue,100);});

// Every independent edit has a mathematically specified effect.
test('cost controls: tax rate uses purchase value annually then divides by twelve',()=>{const a=patch({taxRatePercent:2});near(calculate(a).tax,200);near(calculate(a).totalOutflow,1190);near(calculate(a).cashflow,610);});
test('cost controls: a tax-only edit cannot change other cost components or financing',()=>{const old=calculate(modern()),next=calculate(patch({taxRatePercent:2}));for(const k of ['loan','mortgage','downPayment','insurance','hoa','maintenance','capex','management','closingCosts','cashInvested'])assert.equal(next[k],old[k]);});
test('cost controls: annual insurance converts correctly, not twelve times too high',()=>{const old=calculate(modern()),m=calculate(patch({insuranceAnnual:720}));near(m.insurance,60);near(m.totalOutflow-old.totalOutflow,10);near(m.firstYearOutlay-old.firstYearOutlay,120);});
test('cost controls: an insurance-only edit leaves annual tax and reserve untouched',()=>{const old=calculate(modern()),m=calculate(patch({insuranceAnnual:720}));for(const k of ['tax','maintenance','hoa','mortgage','cashInvested'])assert.equal(m[k],old[k]);});
test('cost controls: a monthly maintenance edit changes only its expense contribution',()=>{const m=calculate(patch({maintenanceValue:150}));near(m.maintenance,150);near(m.totalOutflow,1140);near(m.cashflow,660);near(m.cashInvested,43600);});
test('cost controls: monthly reserve no longer moves with rent',()=>{const a=modern();near(calculate({...a,rent:4000}).maintenance,100);});
test('cost controls: value-based reserve is percent of home value per YEAR',()=>{const m=calculate(patch({maintenanceBasis:'home-value',maintenanceValue:2}));near(m.maintenance,200);});
test('cost controls: value-based reserve moves with price, not rent',()=>{const a=patch({maintenanceBasis:'home-value',maintenanceValue:1});near(calculate({...a,price:240000}).maintenance,200);near(calculate({...a,rent:6000}).maintenance,100);});
test('cost controls: switching maintenance units preserves every result',()=>{const a=modern(),b=changeCostBasis(a,'maintenanceBasis','home-value'),c=changeCostBasis(b,'maintenanceBasis','monthly');assert.equal(b.costs.maintenanceValue,1);near(c.costs.maintenanceValue,100);assert.deepEqual(calculate(b),calculate(a));assert.deepEqual(calculate(c),calculate(a));});
test('cost controls: percent conversions preserve non-round amounts without truncation',()=>{const a=defaultCalculatorAssumptions(seedProperties[0]);a.costs.maintenanceValue=123.45;const b=changeCostBasis(a,'maintenanceBasis','home-value');near(calculate(a).totalOutflow,calculate(b).totalOutflow);near(changeCostBasis(b,'maintenanceBasis','monthly').costs.maintenanceValue,123.45);});
test('cost controls: dormant legacy tax insurance maintenance and closing cannot double-charge',()=>{const a=modern(),b={...a,taxAnnual:123456,insuranceMonthly:777,maintenancePercent:65,closingPercent:22};assert.deepEqual(calculate(b),calculate(a));});
test('cost controls: routine and larger-replacement reserves stay distinct',()=>{const m=calculate(patch({maintenanceValue:150}));near(m.maintenance,150);near(m.capex,60);near(m.noiMonthly,1220);near(m.cashflow,660);});
test('cost controls: HOA off excludes the fee without deleting the entered amount',()=>{const a=patch({hoaApplicable:false}),m=calculate(a);assert.equal(a.hoaMonthly,100);assert.equal(m.hoa,0);near(m.totalOutflow,990);near(m.cashInvested,43600);});
test('cost controls: turning HOA back on restores the exact amount',()=>{const a=patch({hoaApplicable:false});a.costs.hoaApplicable=true;assert.deepEqual(calculate(a),calculate(modern()));});
test('cost controls: zero HOA is legitimate even when marked applicable',()=>{const a=modern();a.hoaMonthly=0;assert.deepEqual(validateAssumptions(a),[]);assert.equal(calculate(a).hoa,0);});
test('cost controls: percentage closing costs change upfront but never monthly costs',()=>{const m=calculate(patch({closingValue:4})),old=calculate(modern());near(m.closingCosts,4800);near(m.cashInvested,44800);assert.equal(m.cashflow,old.cashflow);assert.equal(m.totalOutflow,old.totalOutflow);assert.equal(m.capRate,old.capRate);near(m.firstYearOutlay-old.firstYearOutlay,1200);});
test('cost controls: fixed closing costs are charged exactly once',()=>{const m=calculate(patch({closingBasis:'amount',closingValue:5000}));near(m.cashInvested,45000);near(m.totalOutflow,1090);near(m.firstYearOutlay,58080);});
test('cost controls: switching closing units preserves the entire result',()=>{const a=modern(),b=changeCostBasis(a,'closingBasis','amount');assert.equal(b.costs.closingValue,3600);assert.deepEqual(calculate(b),calculate(a));assert.deepEqual(calculate(changeCostBasis(b,'closingBasis','percent')),calculate(a));});
test('cost controls: percentage closing costs scale with purchase price',()=>{const a=modern();near(calculate({...a,price:240000}).closingCosts,7200);});
test('cost controls: fixed closing amount does not scale with purchase price',()=>{const a=patch({closingBasis:'amount',closingValue:5000});near(calculate({...a,price:240000}).closingCosts,5000);});
test('cost controls: initial repairs are also one-time, without altering monthly costs',()=>{const a=modern(),m=calculate({...a,initialRepairs:15000});near(m.totalOutflow,1090);near(m.firstYearOutlay-calculate(a).firstYearOutlay,5000);});
test('cost controls: first-year outlay is upfront plus exactly twelve monthly outflows',()=>{const a=modern(),m=calculate(a);near(m.firstYearOutlay,56680);near(m.firstYearOutlay,m.cashInvested+m.totalOutflow*12);});
test('cost controls: zero-rate mortgage and all-cash PMI handling remain intact',()=>{const a=modern(),m=calculate({...a,downPercent:100,mortgageInsuranceMonthly:700});near(m.mortgage,0);near(m.totalOutflow,590);assert.deepEqual(amortization({...a,downPercent:100}),[]);});
test('cost controls: no cash invested still yields null cash-on-cash, never infinity',()=>{const a=patch({closingValue:0});Object.assign(a,{downPercent:0,initialRepairs:0});assert.equal(calculate(a).cashOnCash,null);});
test('cost controls: zeros are valid inputs, not missing values',()=>{const a=patch({taxRatePercent:0,insuranceAnnual:0,maintenanceValue:0,hoaApplicable:false,closingValue:0});assert.deepEqual(validateAssumptions(a),[]);const m=calculate(a);for(const key of ['tax','insurance','maintenance','hoa','closingCosts'])assert.equal(m[key],0);});

// Validation / serialization / migration through the existing workspace mechanism.
test('cost controls: missing, nonfinite, negative and string cost values are rejected',()=>{for(const key of ['taxRatePercent','insuranceAnnual','maintenanceValue','closingValue'])for(const value of [undefined,NaN,Infinity,-1,'5',null])assert.ok(validateAssumptions(patch({[key]:value})).length,`${key}:${value}`);});
test('cost controls: malformed nested cost objects cannot enter calculations',()=>{for(const value of [null,[],42,'fake'])assert.throws(()=>calculate({...legacy(),costs:value}),RangeError);});
test('cost controls: invalid unit enums and nonboolean HOA flags are rejected',()=>{for(const input of [{maintenanceBasis:'rent'},{closingBasis:'monthly'},{hoaApplicable:'false'},{hoaApplicable:0}])assert.ok(validateOwnershipCosts(patch(input).costs).length);});
test('cost controls: upper dollar and closing-percentage limits are enforced',()=>{for(const input of [{insuranceAnnual:1200001},{maintenanceValue:1000001},{closingValue:31},{closingBasis:'amount',closingValue:100000001}])assert.ok(validateAssumptions(patch(input)).length);});
test('cost controls: invalid unit change is rejected atomically',()=>{const a=modern(),copy=encode(a);assert.throws(()=>changeCostBasis(a,'maintenanceBasis','bad'),RangeError);assert.throws(()=>changeCostBasis(a,'closingBasis','monthly'),RangeError);assert.equal(encode(a),copy);});
test('cost controls: excessive closing-percentage conversion keeps the original amount intact',()=>{const a=patch({closingBasis:'amount',closingValue:60000}),copy=encode(a);assert.throws(()=>changeCostBasis(a,'closingBasis','percent'),/cannot be represented/);assert.equal(encode(a),copy);});
test('cost controls: older backups migrate to an empty calculator without losing decisions',()=>{const w=freshWorkspace();delete w.calculator;w.savedIds=['sample-2'];w.decisions.participants[0].name='My profile';const restored=parseWorkspace(encode(w));assert.deepEqual(restored.calculator,freshCalculator());assert.deepEqual(restored.savedIds,w.savedIds);assert.deepEqual(restored.decisions,w.decisions);});
test('cost controls: old saved scenario assumptions stay unchanged during backup migration',()=>{const w=freshWorkspace();delete w.calculator;w.scenarios=[{id:'legacy',name:'Legacy',propertyId:'sample-1',savedAt:1,assumptions:legacy()}];assert.deepEqual(parseWorkspace(encode(w)).scenarios,w.scenarios);});
test('cost controls: separate property drafts and active property round-trip exactly',()=>{const w=freshWorkspace();w.calculator={version:1,activePropertyId:'sample-2',drafts:{'sample-1':modern(),'sample-2':patch({closingBasis:'amount',closingValue:8750})}};assert.deepEqual(parseWorkspace(encode(w)),w);});
test('cost controls: nested cost units survive saved-scenario import',()=>{const w=freshWorkspace();w.scenarios=[{id:'s',name:'Value reserve',propertyId:'sample-1',savedAt:1,assumptions:patch({maintenanceBasis:'home-value',maintenanceValue:1.5})}];assert.deepEqual(parseWorkspace(encode(w)).scenarios,w.scenarios);});
test('cost controls: malformed calculator draft is rejected instead of silently reset',()=>{const w=freshWorkspace();w.calculator.drafts['sample-1']=patch({insuranceAnnual:-1});assert.throws(()=>parseWorkspace(encode(w)),/calculator cost/);});
test('cost controls: malformed calculator metadata is rejected',()=>{for(const c of [null,[],{version:2},{version:1,activePropertyId:'sample-1',drafts:[]}])assert.throws(()=>parseCalculator(c),/calculator/);});
test('cost controls: prototype and unscoped property IDs are rejected',()=>{for(const id of ['__proto__','constructor','sample-1/../../','arbitrary']){const c=JSON.parse(`{"version":1,"activePropertyId":"sample-1","drafts":{"${id}":${encode(modern())}}}`);assert.throws(()=>parseCalculator(c),/calculator/);}});
test('cost controls: oversized draft collections are rejected',()=>{const drafts=Object.fromEntries(Array.from({length:561},(_,i)=>['sample-'+(i+1),modern()]));assert.throws(()=>parseCalculator({version:1,activePropertyId:'sample-1',drafts}),/calculator/);});
test('cost controls: invalid active property key is rejected',()=>assert.throws(()=>parseCalculator({version:1,activePropertyId:'__proto__',drafts:{}}),/calculator/));
test('cost controls: per-home edits persist with the unchanged local storage key',()=>{const values=new Map();globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};try{const w=freshWorkspace();w.calculator.drafts['sample-1']=patch({insuranceAnnual:1111});assert.equal(saveWorkspace(w),true);assert.ok(values.has(STORAGE_KEY));assert.deepEqual(loadWorkspace().workspace,w);}finally{delete globalThis.localStorage;}});
test('cost controls: denied storage returns false, never a false success',()=>{Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('Denied')}});try{assert.equal(saveWorkspace(freshWorkspace()),false);}finally{delete globalThis.localStorage;}});
test('cost controls: invalid saved cost data keeps a recovery copy',()=>{const w=freshWorkspace();w.calculator.drafts['sample-1']=patch({closingValue:-1});const raw=encode(w),values=new Map([[STORAGE_KEY,raw]]);globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};try{const result=loadWorkspace();assert.equal(values.get(STORAGE_KEY+'.recovery'),raw);assert.match(result.notice,/recovery/);}finally{delete globalThis.localStorage;}});

// Consumer-facing labels, provenance and report numbers must describe effective inputs.
test('cost controls: reports contain active units and one-time closing costs',()=>{const rows=modelAssumptionsRows(patch({maintenanceBasis:'home-value',maintenanceValue:1,closingBasis:'amount',closingValue:5000})),text=encode(rows);assert.match(text,/% of home value per year/);assert.match(text,/ONE-TIME/);assert.ok(rows.some(([k,v])=>k==='Estimated closing costs ($; ONE-TIME)'&&v===5000));assert.ok(!rows.some(([k])=>k==='Maintenance (% of gross rent)'));});
test('cost controls: reports export calculated tax, not the dormant legacy annual input',()=>{const a=patch({taxRatePercent:2});const rows=modelAssumptionsRows(a);assert.equal(rows.find(([k])=>k==='Derived property taxes ($/year)')[1],2400);});
test('cost controls: reports exclude dormant HOA while showing applicability',()=>{const rows=modelAssumptionsRows(patch({hoaApplicable:false}));assert.ok(rows.some(([k,v])=>k==='HOA applies'&&v==='No'));assert.ok(rows.some(([k,v])=>k==='Effective HOA ($/month)'&&v===0));});
test('cost controls: old report rows retain their documented legacy basis',()=>{const rows=modelAssumptionsRows(legacy());assert.ok(rows.some(([k,v])=>k==='Maintenance (% of gross rent)'&&v===5));});
test('cost controls: visible conversions agree with calculated totals and units',()=>{const hints=costHints(modern());assert.match(hints.taxRatePercent,/\$1,200.00 \/ year · \$100.00 \/ month/);assert.match(hints.insuranceAnnual,/\$50.00/);assert.match(hints.closingValue,/once at purchase. Not a monthly charge/);});
test('cost controls: cents format is consistent including exact zeros',()=>{assert.equal(preciseMoney(120.5),'$120.50');assert.equal(preciseMoney(0),'$0.00');assert.equal(preciseMoney(-0.0001),'$0.00');});
test('cost controls: reference calculation matches each displayed component sum',()=>{const a=modern(),c=resolvedOwnershipCosts(a),m=calculate(a);near(m.totalOutflow,m.mortgage+c.tax+c.insurance+c.hoa+c.maintenance+m.management+m.capex);near(m.cashflow,m.effectiveRent-m.totalOutflow);});
