import test from 'node:test';
import assert from 'node:assert/strict';
import { seedProperties } from '../build/data.js';
import { mortgagePayment } from '../build/finance.js';
import { freshWorkspace, parseWorkspace } from '../build/storage.js';
import { freshDecisions, newParticipant, activeParticipant, emptyPriorities, exampleBudget, defaultLifeInputs, calculateLife, validLife, validBudget, validStress, validPriorities, assessFit, sharedFit, emptyDecisionHome, tourQuestions, parseDecisions, pruneDecisions } from '../build/decision-engine.js';
const p=seedProperties[0], b=exampleBudget(),a=defaultLifeInputs(p),near=(x,y)=>assert.ok(Math.abs(x-y)<1e-7,`${x} != ${y}`);
const clone=x=>structuredClone(x);
const d=()=>freshDecisions();
const fixture=()=>{const x=d();x.participants[0].budget=clone(b);x.participants[0].life[p.id]=clone(a);x.homes[p.id]=emptyDecisionHome();return x;};
const bad=mutate=>{const x=fixture();mutate(x);assert.throws(()=>parseDecisions(x),/decision data/);};

test('empty workspace has one unconfigured profile, no fake household data',()=>{assert.equal(d().participants.length,1);assert.equal(activeParticipant(d()).budget,null);assert.equal(d().snapshots.length,0)});
test('fresh profile objects do not share mutable state',()=>{const x=d(),y=d();x.participants[0].priorities.minBeds=9;assert.equal(y.participants[0].priorities.minBeds,0)});
test('explicit sample budget is labeled sample',()=>assert.equal(b.example,true));
test('baseline separates monthly living from initial purchase costs',()=>{const m=calculateLife(p.price,b,a);near(m.mortgage,mortgagePayment(260000,6.5,30));near(m.housing,m.mortgage+400+125+250+271);near(m.leftover,7000-m.housing-1600-800);near(m.upfront,65000+9750+1500);near(m.cashRemaining,33750)});
test('cushion is a comparison target and is not subtracted twice',()=>{const x=calculateLife(p.price,b,a),y=calculateLife(p.price,{...b,cushion:999},a);near(x.leftover,y.leftover);near(y.cushionGap,y.leftover-999)});
test('zero-rate mortgage remains finite and exact',()=>near(calculateLife(p.price,b,{...a,interestRate:0}).mortgage,260000/360));
test('cash purchase has no mortgage or mortgage insurance',()=>{const m=calculateLife(p.price,b,{...a,downPercent:100,mortgageInsurance:500});assert.equal(m.mortgage,0);assert.equal(m.pmi,0)});
test('mortgage insurance is counted exactly once for a financed purchase',()=>near(calculateLife(p.price,b,{...a,mortgageInsurance:125}).housing-calculateLife(p.price,b,a).housing,125));
test('income shock lowers monthly remainder but not upfront cash',()=>{const x=calculateLife(p.price,b,a),y=calculateLife(p.price,b,a,'income',{incomeDrop:20,expenseIncrease:300,repairCost:5000});near(x.leftover-y.leftover,1400);near(x.cashRemaining,y.cashRemaining)});
test('expense shock affects monthly remainder only',()=>{const x=calculateLife(p.price,b,a),y=calculateLife(p.price,b,a,'expenses',{incomeDrop:20,expenseIncrease:300,repairCost:5000});near(x.leftover-y.leftover,300);near(x.cashRemaining,y.cashRemaining)});
test('one-time repair affects cash but never recurs as monthly spending',()=>{const x=calculateLife(p.price,b,a),y=calculateLife(p.price,b,a,'repair',{incomeDrop:20,expenseIncrease:300,repairCost:5000});near(x.leftover,y.leftover);near(x.cashRemaining-y.cashRemaining,5000);assert.equal(y.incomeLoss,0);assert.equal(y.expenseStress,0)});
test('100% income loss does not get clamped to a false positive balance',()=>assert.ok(calculateLife(p.price,b,a,'income',{incomeDrop:100,expenseIncrease:0,repairCost:0}).leftover<0));
test('negative cash remainder exposes the full shortfall',()=>near(calculateLife(p.price,{...b,cash:0},a).cashRemaining,-76250));
test('initial repair and unexpected repair costs are counted separately',()=>{const x=calculateLife(p.price,b,{...a,repairs:1000},'repair',{incomeDrop:0,expenseIncrease:0,repairCost:5000});near(x.cashRemaining,27750)});
test('zero income and zero expenses are valid, not treated as missing',()=>assert.ok(validBudget({income:0,expenses:0,savings:0,cash:0,cushion:0,example:false})));
test('life model is deterministic and does not mutate inputs',()=>{const budget=clone(b),inputs=clone(a);assert.deepEqual(calculateLife(p.price,budget,inputs),calculateLife(p.price,budget,inputs));assert.deepEqual(budget,b);assert.deepEqual(inputs,a)});
test('all 60 listings produce finite results with a conserving monthly budget',()=>{for(const p of seedProperties){const m=calculateLife(p.price,b,defaultLifeInputs(p));assert.ok(Object.values(m).every(Number.isFinite));near(m.income,m.housing+m.expenses+m.savings+m.leftover)}});
test('duplex owner-occupant calculation never offsets costs with fictional rent',()=>{const duplex=seedProperties.find(p=>p.type==='Duplex');const x=calculateLife(duplex.price,b,defaultLifeInputs(duplex));const y=calculateLife(duplex.price,b,defaultLifeInputs({...duplex,rent:999999}));assert.deepEqual(x,y)});
test('changing fictional price changes default maintenance and loan principal',()=>assert.notEqual(calculateLife(p.price,b,a).housing,calculateLife(p.price+10000,b,defaultLifeInputs({...p,price:p.price+10000})).housing));
test('invalid numeric input is never allowed into a calculation',()=>{for(const v of [NaN,Infinity,-1,'325000',null])assert.throws(()=>calculateLife(v,b,a),RangeError)});
test('nonfinite and negative household values are rejected',()=>{for(const value of [NaN,Infinity,-1,'7000',null])assert.equal(validBudget({...b,income:value}),false)});
test('all ownership fields are bounded and fractional years are rejected',()=>{assert.equal(validLife({...a,downPercent:101}),false);assert.equal(validLife({...a,years:1.5}),false);assert.equal(validLife({...a,closingPercent:-1}),false);assert.equal(validLife({...a,utilities:NaN}),false)});
test('invalid stress type and limits are rejected',()=>{assert.throws(()=>calculateLife(p.price,b,a,'unknown'));assert.equal(validStress({incomeDrop:101,expenseIncrease:0,repairCost:0}),false)});
test('requirements compare price, city, type, bedrooms and area with exact boundaries',()=>{const req={...emptyPriorities(),city:p.city.toUpperCase(),type:p.type,maxPrice:p.price,minBeds:p.beds,minSqft:p.sqft};assert.equal(assessFit(p,req).length,5);assert.ok(assessFit(p,req).every(x=>x.status==='fits'))});
test('exceeding price or missing numeric must-have is a trade-off',()=>{const list=assessFit(p,{...emptyPriorities(),maxPrice:p.price-1,minBeds:p.beds+1,minSqft:p.sqft+1});assert.ok(list.every(x=>x.status==='tradeoff'))});
test('a mentioned garden can support outdoor fit without inventing its condition',()=>{const point=assessFit(p,{...emptyPriorities(),outdoor:true})[0];assert.equal(point.status,'fits');assert.match(point.detail,/not verified/)});
test('missing outdoor feature is unknown rather than a fabricated exclusion',()=>{const point=assessFit({...p,tags:[]},{...emptyPriorities(),outdoor:true})[0];assert.equal(point.status,'unknown')});
test('freeform must-haves are recorded but not guessed from descriptions',()=>assert.equal(assessFit(p,{...emptyPriorities(),notes:'Garage with charger'})[0].status,'unknown'));
test('duplex aggregate bedrooms and floor area cannot establish per-unit fit',()=>{const duplex=seedProperties.find(p=>p.type==='Duplex');const points=assessFit(duplex,{...emptyPriorities(),minBeds:1,minSqft:500});assert.ok(points.every(x=>x.status==='unknown'));assert.match(points[0].detail,/combined/)});
test('shared fit asks for missing priorities rather than calling empty profiles a match',()=>assert.equal(sharedFit(p,d().participants).status,'Add priorities'));
test('shared fit requires every person’s stated requirements',()=>{const x=newParticipant(),y=newParticipant('person-two','Alex');x.priorities.minBeds=3;y.priorities.minBeds=4;assert.equal(sharedFit(p,[x,y]).status,'Trade-offs to discuss');y.priorities.minBeds=3;assert.equal(sharedFit(p,[x,y]).met,true)});
test('unknown requirements stop a definitive shared match',()=>{const x=newParticipant();x.priorities.notes='Near work';assert.equal(sharedFit(p,[x]).status,'Needs verification')});
test('numeric priority caps are validated',()=>{assert.equal(validPriorities({...emptyPriorities(),maxPrice:-1}),false);assert.equal(validPriorities({...emptyPriorities(),type:'Castle'}),false)});
test('tour checklist begins unresolved and never invents answers',()=>{const q=tourQuestions(p,emptyPriorities(),emptyDecisionHome());assert.ok(q.length>=5);assert.ok(q.every(x=>!x.resolved&&x.answer===''&&x.source===''))});
test('condos get association questions and duplexes get unit breakdown questions',()=>{for(const type of ['Condo','Duplex']){const prop=seedProperties.find(x=>x.type===type);assert.ok(tourQuestions(prop,emptyPriorities(),emptyDecisionHome()).some(q=>q.id===(type==='Condo'?'hoa':'units')))}});
test('tour requirements add relevant light and outdoor questions',()=>{const ids=tourQuestions(p,{...emptyPriorities(),outdoor:true,light:true},emptyDecisionHome()).map(q=>q.id);assert.ok(ids.includes('outdoor'));assert.ok(ids.includes('light'))});
test('stored answers and custom questions survive changes to priorities',()=>{const h=emptyDecisionHome();h.questions['question-one']={id:'question-one',text:'Are pets permitted?',answer:'User report',source:'Phone note',resolved:true,updatedBy:'person-me',updatedAt:1,custom:true};assert.equal(tourQuestions(p,emptyPriorities(),h).at(-1).answer,'User report')});
test('old workspace backups without decision extension migrate safely',()=>{const w=freshWorkspace();delete w.decisions;w.savedIds=['sample-1'];const result=parseWorkspace(JSON.stringify(w));assert.deepEqual(result.decisions,d());assert.deepEqual(result.savedIds,['sample-1'])});
test('expanded backups round-trip all new data',()=>{const w=freshWorkspace();w.decisions=fixture();assert.deepEqual(parseWorkspace(JSON.stringify(w)),w)});
test('parsed decisions are cloned, not shared with external inputs',()=>{const raw=fixture(),out=parseDecisions(raw);out.participants[0].name='Edited';assert.equal(raw.participants[0].name,'You')});
test('foreign active profile and duplicate profile IDs are rejected',()=>{bad(x=>x.activeParticipantId='person-missing');bad(x=>x.participants.push(clone(x.participants[0])))});
test('zero or more than eight participants are rejected',()=>{bad(x=>x.participants=[]);bad(x=>x.participants=Array.from({length:9},(_,i)=>newParticipant('person-'+i,'Person')))});
test('nonfinite ownership inputs in imports are rejected',()=>bad(x=>x.participants[0].life[p.id].interestRate=Infinity));
test('dangerous property keys in imports are rejected',()=>bad(x=>x.homes=JSON.parse('{"__proto__":{}}')));
test('unknown review authors are rejected',()=>bad(x=>x.homes[p.id].reviews['person-missing']={stance:'Interested',note:'',updatedAt:0}));
test('malformed review stance is rejected',()=>bad(x=>x.homes[p.id].reviews['person-me']={stance:'Definitely approved',note:'',updatedAt:0}));
test('unknown stages are rejected',()=>bad(x=>x.homes[p.id].stage='Approved loan'));
test('resolved answers must include both an answer and source',()=>bad(x=>x.homes[p.id].questions.roof={id:'roof',text:'Roof?',answer:'',source:'',resolved:true,updatedBy:'person-me',updatedAt:0,custom:false}));
test('imported questions with mismatched IDs are rejected',()=>bad(x=>x.homes[p.id].questions.roof={id:'systems',text:'Roof?',answer:'',source:'',resolved:false,updatedBy:'person-me',updatedAt:0,custom:false}));
test('malformed visit dates and oversized notes are rejected',()=>{bad(x=>x.homes[p.id].visit.date='tomorrow');bad(x=>x.homes[p.id].visit.notes='a'.repeat(5001))});
test('snapshot validation preserves a frozen original price and exact math',()=>{const x=fixture();x.snapshots.push({id:'life-test',name:'Sample plan',propertyId:p.id,participantId:'person-me',savedAt:1,price:p.price,budget:clone(b),inputs:clone(a),stress:'repair',stressInputs:{incomeDrop:20,expenseIncrease:300,repairCost:5000}});const saved=parseDecisions(x).snapshots[0];assert.equal(saved.price,p.price);near(calculateLife(saved.price,saved.budget,saved.inputs,saved.stress,saved.stressInputs).cashRemaining,28750)});
test('deleting a property removes associated plans, answers, and snapshots',()=>{const x=fixture();const result=pruneDecisions(x,new Set(['sample-2','sample-1']));assert.ok(result.homes['sample-1']);pruneDecisions(x,new Set(['sample-2']));assert.equal(Object.keys(x.homes).length,0);assert.equal(Object.keys(x.participants[0].life).length,0)});
