import test from 'node:test';
import assert from 'node:assert/strict';
import { mortgagePayment, calculate, validateAssumptions, defaultAssumptions, amortization, filterProperties, defaultFilters, median, csvCell, toCSV } from '../build/finance.js';
import { seedProperties } from '../build/data.js';
import { escapeHTML } from '../build/ui.js';

const near=(actual,expected,epsilon=.00001)=>assert.ok(Math.abs(actual-expected)<epsilon,`${actual} ≈ ${expected}`);
const base={price:120000,downPercent:25,interestRate:0,years:15,rent:2000,taxAnnual:1200,insuranceMonthly:100,hoaMonthly:50,vacancyPercent:10,maintenancePercent:5,managementPercent:10,capexPercent:3,closingPercent:3,initialRepairs:10000,mortgageInsuranceMonthly:0};

test('fixed-rate payment agrees with known 200k / 6% / 30-year example',()=>near(mortgagePayment(200000,6,30),1199.1010503055138));
test('zero-interest loan divides principal evenly',()=>assert.equal(mortgagePayment(90000,0,15),500));
test('no principal means no loan payment',()=>assert.equal(mortgagePayment(0,6.5,30),0));
test('tiny positive rates remain numerically stable',()=>near(mortgagePayment(120000,1e-9,30),120000/360,.0001));
test('invalid mortgage inputs fail explicitly',()=>{for(const args of [[-1,6,30],[100,-1,30],[100,6,0],[NaN,6,30],[100,Infinity,30]])assert.throws(()=>mortgagePayment(...args),RangeError)});
test('calculator uses correct loan and down payment',()=>{const m=calculate(base);assert.equal(m.loan,90000);assert.equal(m.downPayment,30000);assert.equal(m.mortgage,500)});
test('vacancy reduces rent and management uses collected rent',()=>{const m=calculate(base);assert.equal(m.vacancy,200);assert.equal(m.effectiveRent,1800);assert.equal(m.management,180)});
test('annual taxes convert to monthly; expenses include maintenance',()=>{const m=calculate(base);assert.equal(m.tax,100);assert.equal(m.maintenance,100);assert.equal(m.operatingExpenses,530)});
test('NOI excludes debt and capital reserves',()=>{const m=calculate(base);assert.equal(m.noiMonthly,1270);assert.equal(m.capex,60);near(m.capRate,12.7)});
test('cash flow subtracts financing and capital reserves',()=>{const m=calculate(base);assert.equal(m.cashflow,710);assert.equal(m.totalOutflow,1090)});
test('cash invested includes closing costs and initial repairs',()=>{const m=calculate(base);assert.equal(m.cashInvested,43600);near(m.cashOnCash,8520/43600*100)});
test('all-cash financing and mortgage insurance both become zero',()=>{const m=calculate({...base,downPercent:100,mortgageInsuranceMonthly:500});assert.equal(m.loan,0);assert.equal(m.mortgage,0);assert.equal(m.cashflow,1210)});
test('mortgage insurance reduces cash flow but not NOI or cap rate',()=>{const m=calculate({...base,mortgageInsuranceMonthly:120});assert.equal(m.cashflow,590);assert.equal(m.noiMonthly,1270);near(m.capRate,12.7)});
test('zero invested cash gives null return, never infinity',()=>{const m=calculate({...base,downPercent:0,closingPercent:0,initialRepairs:0});assert.equal(m.cashOnCash,null)});
test('zero rent and full vacancy remain finite',()=>{for(const patch of [{rent:0},{vacancyPercent:100}]){const m=calculate({...base,...patch});assert.equal(m.effectiveRent,0);assert.ok(Number.isFinite(m.cashflow))}});
test('negative and nonfinite inputs are rejected',()=>{for(const patch of [{price:0},{rent:-1},{downPercent:101},{interestRate:NaN},{hoaMonthly:Infinity},{years:0}])assert.ok(validateAssumptions({...base,...patch}).length)});
test('valid assumptions pass schema validation',()=>assert.deepEqual(validateAssumptions(base),[]));
test('all fixtures have valid model assumptions',()=>seedProperties.forEach(p=>assert.equal(validateAssumptions(defaultAssumptions(p)).length,0)));
test('amortization reaches zero and conserves original principal',()=>{const a={...base,interestRate:6.5,years:30};const schedule=amortization(a);assert.equal(schedule.length,30);assert.equal(schedule.at(-1).balance,0);near(schedule.reduce((sum,y)=>sum+y.principal,0),90000,.01);near(schedule.reduce((sum,y)=>sum+y.principal+y.interest,0),calculate(a).mortgage*360,.01)});
test('zero-rate amortization has no interest',()=>{const schedule=amortization(base);assert.equal(schedule.length,15);assert.equal(schedule.at(-1).balance,0);assert.equal(schedule.reduce((sum,y)=>sum+y.interest,0),0)});
test('all-cash amortization is empty',()=>assert.deepEqual(amortization({...base,downPercent:100}),[]));
test('search matches case-insensitive words across location fields',()=>{const r=filterProperties(seedProperties,{...defaultFilters,query:'LINCOLN willow'});assert.equal(r.length,1);assert.equal(r[0].id,'sample-1')});
test('filters compose with AND semantics',()=>{const r=filterProperties(seedProperties,{...defaultFilters,city:'Lincoln',maxPrice:300000,minBeds:3,type:'Townhouse'});assert.deepEqual(r.map(x=>x.id),['sample-4'])});
test('area and cash-flow filters apply actual computed values',()=>{const r=filterProperties(seedProperties,{...defaultFilters,minSqft:1800,positiveOnly:true});assert.ok(r.length);r.forEach(p=>{assert.ok(p.sqft>=1800);assert.ok(calculate(defaultAssumptions(p)).cashflow>=0)})});
test('search supports no-results state',()=>assert.equal(filterProperties(seedProperties,{...defaultFilters,query:'never-a-real-fixture-zzzz'}).length,0));
test('price sort is ascending and does not mutate input',()=>{const before=seedProperties.map(p=>p.id);const r=filterProperties(seedProperties,defaultFilters,'price-asc');assert.equal(r[0].price,198000);assert.equal(r.at(-1).price,895000);assert.deepEqual(seedProperties.map(p=>p.id),before)});
test('cash-flow sort uses computed values, not a seeded score',()=>{const r=filterProperties(seedProperties,defaultFilters,'cashflow');for(let i=1;i<r.length;i++)assert.ok(calculate(defaultAssumptions(r[i-1])).cashflow>=calculate(defaultAssumptions(r[i])).cashflow)});
test('cap-rate sort uses NOI divided by price',()=>{const r=filterProperties(seedProperties,defaultFilters,'caprate');for(let i=1;i<r.length;i++)assert.ok(calculate(defaultAssumptions(r[i-1])).capRate>=calculate(defaultAssumptions(r[i])).capRate)});
test('median handles even, odd, and empty inputs',()=>{assert.equal(median([]),0);assert.equal(median([9,1,4]),4);assert.equal(median([9,1,5,3]),4)});
test('CSV neutralizes dangerous text while preserving numeric negatives',()=>{assert.equal(csvCell('=SUM(1,2)'),`"'=SUM(1,2)"`);assert.equal(csvCell('  @command'),`"'  @command"`);assert.equal(csvCell(-120),'"-120"')});
test('CSV escapes quotes and keeps commas/newlines in cells',()=>{assert.equal(csvCell('A "test", home'),'"A ""test"", home"');assert.equal(toCSV([['A','B'],['C\nD',2]]),'\uFEFF"A","B"\r\n"C\nD","2"')});
test('user-controlled HTML is escaped before rendering',()=>assert.equal(escapeHTML('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;'));
