"""Feature #3: actual Chromium interactions with isolated storage and blocked networking.
Assertions measure local behavior, not native cross-session persistence or real commutes.
"""
from pathlib import Path
import ast,json,shutil,subprocess
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'dist/index.html').read_text()
DATA=json.loads(subprocess.check_output(['node','--input-type=module','-e','import {seedProperties} from "./build/data.js";console.log(JSON.stringify(seedProperties));'],cwd=ROOT))
HOMES={p['id']:p for p in DATA}
BASE=sorted(DATA,key=lambda h:-h['addedAt'])
checks=[];errors=[];requests=[];audits=[];pages=[]
STORAGE="""(seed)=>{const v=new Map(Object.entries(seed||{}));Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>v.get(k)??null,setItem:(k,x)=>v.set(k,String(x)),removeItem:k=>v.delete(k),clear:()=>v.clear()}});window.__fetches=[];window.fetch=(...args)=>{window.__fetches.push(String(args[0]));return Promise.reject(new Error('Network disabled'));};}"""
CONTRAST=next(ast.literal_eval(n.value) for n in ast.parse((ROOT/'tests/ranking_theme_browser.py').read_text()).body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='CONTRAST' for t in n.targets))
def check(name,ok):
 checks.append({'name':name,'passed':bool(ok)});print(('PASS ' if ok else 'FAIL ')+name,flush=True);assert ok,name
def store(p):return p.evaluate('JSON.parse(localStorage.getItem("haven.workspace.v1")||"{}")')
def memory(p):return store(p).get('rejections',{'version':1,'enabled':True,'records':{}})
def close(p):
 if p.locator('dialog[open]').count():p.locator('.modal-close').click()
def nav(p,key):
 close(p)
 if p.viewport_size['width']<=780:p.locator('[data-action="menu"]').click()
 p.locator(f'.nav-item[data-page="{key}"]').click()
def prefs(p):
 close(p)
 if p.locator('#preference-panel').count():p.locator('#preference-panel [data-action="preferences-open"]').click()
 else:
  if p.viewport_size['width']<=780:p.locator('[data-action="menu"]').click()
  p.locator('.nav-item[data-action="preferences-open"]').click()
def search(p,id):p.locator('#property-search').fill(HOMES[id]['name'])
def pick(p,reason):p.locator(f'.pass-chip').filter(has_text=reason).click()
def passhome(p,id,reason='HOA too high',note=''):
 close(p);search(p,id);p.locator(f'.property-card [data-action="pass-open"][data-id="{id}"]').click();pick(p,reason)
 if note:p.locator('#pass-note').fill(note)
 p.locator('#pass-form button[type="submit"]').click()
def ids(p):return p.locator('.property-card').evaluate_all('es=>es.map(e=>e.dataset.property)')
def send(p,text):
 if not p.locator('#haven-assistant').is_visible():p.locator('#assistant-launcher').click()
 p.locator('#assistant-input').fill(text);p.locator('#assistant-send').click();p.wait_for_function('document.querySelector("#assistant-working").hidden')
 return p.locator('.from-haven').last

def audit(p,name):
 result=p.evaluate(CONTRAST);audits.append({'name':name,**result})
 if result['failures']:print(json.dumps(result['failures'],indent=2),flush=True)
 check(name+' text contrast',result['count']>0 and not result['failures'])
def nooverflow(p):return p.evaluate('document.documentElement.scrollWidth<=innerWidth+1 && [...document.querySelectorAll("dialog[open]")].every(d=>d.scrollWidth<=d.clientWidth+1)')
def download(p,selector):
 with p.expect_download(timeout=6000) as pending:p.locator(selector).click()
 return Path(pending.value.path()).read_text(encoding='utf-8-sig')
def make_seed(js):
 raw=subprocess.check_output(['node','--input-type=module','-e','import {seedProperties as data} from "./build/data.js";import {freshWorkspace} from "./build/storage.js";import {passProperty} from "./build/rejection-engine.js";const w=freshWorkspace();'+js+';console.log(JSON.stringify(w));'],cwd=ROOT).decode()
 return {'haven.workspace.v1':raw.strip()}

with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path=shutil.which('chromium') or shutil.which('google-chrome'),args=['--no-sandbox'])
 ctx=browser.new_context(viewport={'width':1440,'height':1100},reduced_motion='reduce',accept_downloads=True)
 ctx.route('**/*',lambda route:(requests.append(route.request.url),route.abort()))
 def load(seed=None,width=1440,height=1100):
  p=ctx.new_page();pages.append(p);p.set_viewport_size({'width':width,'height':height});p.set_default_timeout(7000);p.on('pageerror',lambda e:errors.append(str(e)));p.evaluate(STORAGE,seed);p.set_content(HTML,wait_until='load');return p
 p=load()
 try:
  check('Discover defaults to explicit Recommended order',p.locator('#sort-select').input_value()=='recommended')
  check('Original 60 fixtures and first 12-card page are unchanged',p.locator('#stat-properties').inner_text()=='60' and ids(p)==[h['id'] for h in BASE[:12]])
  check('Your preferences is visible before any pass',p.locator('#preference-panel').is_visible() and 'Two passes' in p.locator('#preference-panel').inner_text())
  check('Global navigation offers preferences from every page',p.locator('.nav-item[data-action="preferences-open"]').count()==1)
  search(p,'sample-5');p.locator('.property-card [data-action="pass-open"]').click()
  check('Reason picker is a native modal with five named choices',p.locator('.pass-modal[open]').count()==1 and p.locator('input[name="reason"]').count()==5)
  p.locator('.pass-transparency summary').click()
  check('Pass dialog discloses source facts, privacy and fictional distance limits',all(x in p.locator('#pass-form').inner_text() for x in ['$415,000','1,280','$320','calculator what-ifs','Together profile','not a real route']) or all(x in p.locator('#pass-form').inner_text() for x in ['$415,000','1,280','$320','calculator what-ifs','Together profile','won’t create a distance rule']))
  p.locator('.pass-transparency summary').click()
  p.locator('#pass-form button[type="submit"]').click()
  check('Submitting without a reason cannot record a pass',not memory(p)['records'])
  pick(p,'HOA too high');check('Choosing a chip does not prematurely save',not memory(p)['records'])
  p.keyboard.press('Escape');check('Escape cancels without recording feedback',p.locator('dialog[open]').count()==0 and not memory(p)['records'])
  passhome(p,'sample-5')
  check('First explicit pass persists under existing workspace key',memory(p)['records']['sample-5']['reason']=='HOA too high')
  check('A passed home is hidden, not deleted from catalogue',p.locator('.property-card').count()==0 and p.locator('#stat-properties').inner_text()=='60')
  check('Keyboard focus lands on a visible review control after the card is removed',p.locator('#preference-panel [data-action="preferences-open"]').evaluate('e=>e===document.activeElement'))
  prefs(p);check('One pass shows pending evidence and no learned rule',p.locator('.preference-rule').count()==0 and '1 of 1' in p.locator('.preference-pending').inner_text())
  close(p);passhome(p,'sample-9')
  check('Two different properties each contribute once',len(memory(p)['records'])==2)
  prefs(p)
  check('Two positive HOA passes activate an exact median threshold',p.locator('.preference-rule').count()==1 and '$270/month' in p.locator('.preference-rule').inner_text() and '2 distinct' in p.locator('.preference-rule').inner_text())
  p.locator('.preference-method summary').click()
  check('The ranking method exposes equal weights, numerical sort priority and unknown data',all(x in p.locator('.preference-method').inner_text() for x in ['equally weighted','cheapest','biggest','does not mean they are nearer','not calculator drafts']))
  p.locator('.preference-method summary').click();p.screenshot(path=str(ROOT/'docs/preferences-light.png'))
  close(p);p.locator('#property-search').fill('')
  expected=[h for h in BASE if h['id'] not in ['sample-5','sample-9']];expected.sort(key=lambda h:int(h['hoaMonthly']>=270))
  check('Discover actually reorders the full catalogue by learned HOA conflict',ids(p)==[h['id'] for h in expected[:12]])
  check('Filtered result count includes 58 remaining homes',p.locator('#result-summary').inner_text().startswith('58 properties'))
  p.locator('[data-action="load-more"]').click()
  check('Pagination appends the next slice of the same learned order',ids(p)==[h['id'] for h in expected[:24]])
  p.locator('#sort-select').select_option('price-asc')
  ascending=sorted(expected,key=lambda h:h['price'])
  check('An explicit price sort takes priority over inferred HOA preference',ids(p)==[h['id'] for h in ascending[:12]])
  check('Preference summary updates when the explicit sort changes','selected sort is kept exactly' in p.locator('#preference-panel').inner_text())
  p.locator('[data-action="passes-toggle"]').click()
  check('Show passed restores both homes to browsing with correct true price order',p.locator('#result-summary').inner_text().startswith('60 properties') and ids(p)[0]=='sample-9')
  check('Passed homes have visible labels and undo, not a destructive delete',p.locator('.property-card[data-property="sample-9"] .passed-property-badge').inner_text()=='Passed' and p.locator('.property-card[data-property="sample-9"] [data-action="pass-undo"]').count()==1)
  p.locator('[data-action="passes-toggle"]').click();p.locator('#sort-select').select_option('recommended')
  reply=send(p,'Show me recommendations')
  check('Assistant explains actual learned HOA influence and threshold','deprioritized high-HOA' in reply.inner_text() and '$270/month' in reply.inner_text())
  rec=reply.locator('.assistant-property').evaluate_all('es=>es.map(e=>e.dataset.recommendation)')
  check('Assistant recommendations exclude passed IDs and prefer below-threshold HOA',len(rec)==3 and all(HOMES[id]['hoaMonthly']<270 and id not in ['sample-5','sample-9'] for id in rec))
  check('Recommendation reasons reference the specific learned threshold','below your learned $270/month threshold' in reply.inner_text())
  check('Chat has a global review action and per-property pass action',p.locator('[data-chat-preferences]').count()==1 and reply.locator('[data-chat-pass]').count()==3)
  check('Past answers are explicitly snapshots, not silently rewritten','Earlier answers are snapshots' in p.locator('#assistant-learning-history').inner_text())
  reply=send(p,'Show me the cheapest home')
  check('Assistant cheapest remains the actual cheapest unpassed home',reply.locator('.assistant-property').first.get_attribute('data-recommendation')==ascending[0]['id'])
  check('Assistant explains why an explicit ranking takes priority','numerical order takes priority' in reply.inner_text())
  reply=send(p,'Use my learned preferences')
  check('Conversation can return to learned ranking without restarting','deprioritized high-HOA' in reply.inner_text())
  p.screenshot(path=str(ROOT/'docs/preferences-assistant-light.png'))
  rid=reply.locator('.assistant-property').first.get_attribute('data-recommendation');reply.locator('[data-chat-pass]').first.click();pick(p,'Other');p.locator('#pass-note').fill('Too small is only a note here.');p.locator('#pass-form button[type="submit"]').click()
  check('Passing directly from chat records the selected home',rid in memory(p)['records'])
  check('Old chat card updates to Passed and allows undo',p.locator(f'[data-chat-pass="{rid}"]').last.inner_text()=='Passed · Undo')
  p.locator(f'[data-chat-pass="{rid}"]').last.click();check('Chat undo removes only that pass',rid not in memory(p)['records'] and len(memory(p)['records'])==2)
  p.locator('.assistant-close').click();prefs(p)
  p.locator('#learning-enabled').uncheck()
  check('Pause is persisted, with rules still visible as paused',memory(p)['enabled']==False and p.locator('.preference-rule .cost-badge').inner_text()=='PAUSED')
  close(p);check('Paused recommendation order returns to original order minus explicit passes',ids(p)==[h['id'] for h in BASE if h['id'] not in ['sample-5','sample-9']][:12])
  reply=send(p,'Show me recommendations');check('Assistant acknowledges pause instead of claiming learned ranking','re-ranking is paused' in reply.inner_text() and 'deprioritized high-HOA' not in reply.inner_text())
  p.locator('.assistant-close').click();prefs(p);p.locator('#learning-enabled').check()
  check('Resuming learning preserves both supporting records',memory(p)['enabled'] and len(memory(p)['records'])==2)
  saved_json=download(p,'.preferences-modal [data-action="export-backup"]');backup=json.loads(saved_json)
  check('Exported backup contains feedback, evidence and enabled state',backup['rejections']==memory(p))
  restored=load({'haven.workspace.v1':saved_json})
  check('App reinitialization restores memory and recommendation order',memory(restored)==backup['rejections'] and ids(restored)==[h['id'] for h in expected[:12]])
  prefs(restored);restored.locator('[data-action="pass-undo"][data-id="sample-5"]').click()
  check('Undo removes evidence immediately and disables a two-pass rule',len(memory(restored)['records'])==1 and restored.locator('.preference-rule').count()==0)
  close(restored);restored.locator('#property-search').fill('The Cedar Loft');check('Undo restores that home to discovery',ids(restored)==['sample-5'])
  # Existing financial plans and notes are independent of preference memory.
  p.bring_to_front();close(p);nav(p,'discover');search(p,'sample-1');p.locator('[data-action="save-toggle"]').click();p.locator('[data-action="compare-toggle"]').click();p.locator('.property-title').click();p.locator('#property-notes').fill('Keep this note');p.locator('[data-action="save-note"]').click();close(p)
  passhome(p,'sample-1','Too small');before_reset=store(p)
  check('Passing a saved home keeps its saved ID, note and comparison','sample-1' in before_reset['savedIds'] and 'sample-1' in before_reset['compareIds'] and before_reset['notes']['sample-1']=='Keep this note')
  nav(p,'saved');check('Explicit saved view still contains the passed home',p.locator('.property-card[data-property="sample-1"] [data-action="pass-undo"]').count()==1)
  prefs(p);p.locator('[data-action="preferences-reset"]').click();p.locator('[data-action="preferences-open"]').last.click()
  check('Reset requires confirmation and cancelling keeps all passes',memory(p)==before_reset['rejections'])
  p.locator('[data-action="preferences-reset"]').click();p.locator('[data-action="preferences-reset-confirm"]').click()
  reset=store(p)
  check('Confirmed reset clears only passes and learned state',reset['rejections']=={'version':1,'enabled':True,'records':{}})
  check('Reset preserves every unrelated stored workspace field',{k:v for k,v in reset.items() if k!='rejections'}=={k:v for k,v in before_reset.items() if k!='rejections'})
  # Other is required, bounded, escaped and never a covert rule.
  nav(p,'discover');search(p,'sample-1');p.locator('.property-card [data-action="pass-open"]').click();pick(p,'Other');p.locator('#pass-form button[type="submit"]').click()
  check('Other requires nonempty free text and does not save prematurely',not memory(p)['records'] and p.locator('#pass-note').get_attribute('required') is not None)
  p.locator('#pass-note').fill('   ');p.locator('#pass-form button[type="submit"]').click();check('Whitespace-only Other note is rejected with an alert',p.locator('#pass-error').is_visible() and not memory(p)['records'])
  p.locator('#pass-note').fill('<img src=x onerror="window.__bad=true"> Price too high');p.locator('#pass-form button[type="submit"]').click();prefs(p)
  check('Free text is rendered as text, not executable markup',p.locator('.pass-note-text').inner_text().startswith('<img') and p.locator('.pass-note-text img').count()==0 and not p.evaluate('!!window.__bad'))
  check('Other is marked note-only and does not train a size/price rule',p.locator('.preference-rule').count()==0 and 'NOTE ONLY' in p.locator('.preference-pending').inner_text())
  p.locator('[data-action="pass-open"][data-id="sample-1"]').click()
  check('Editing an Other pass restores note and required semantics',p.locator('#pass-note').input_value().startswith('<img') and p.locator('#pass-note').get_attribute('required') is not None)
  pick(p,'Price too high');p.locator('#pass-note').fill('');p.locator('#pass-form button[type="submit"]').click()
  check('Editing uses one record instead of counting the same home twice',len(memory(p)['records'])==1 and memory(p)['records']['sample-1']['reason']=='Price too high')
  # Real input forms must not be rebuilt when a chat pass changes memory.
  nav(p,'calculator');p.locator('#calc-rent').fill('');check('Calculator invalid draft is visibly stale before feedback',p.locator('#calc-error').is_visible())
  reply=send(p,'Show me the biggest place');reply.locator('[data-chat-pass]').first.click();pick(p,'Too small');p.locator('#pass-form button[type="submit"]').click()
  check('Feedback from chat preserves incomplete calculator input and stale warning',p.locator('#calc-rent').input_value()=='' and p.locator('#calc-error').is_visible())
  p.locator('.assistant-close').click()
  # Import replacement and rejection of corrupt metadata use existing backup controls.
  imported=load();imported.locator('#backup-input').set_input_files({'name':'feedback.json','mimeType':'application/json','buffer':saved_json.encode()});imported.locator('[data-action="confirm-import"]').click()
  check('Actual file import restores rejection memory and fresh ranking',memory(imported)==backup['rejections'] and ids(imported)==[h['id'] for h in expected[:12]])
  bad=json.loads(saved_json);bad['rejections']['records']['sample-5']['snapshot']['price']='not a number'
  imported.locator('#backup-input').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':json.dumps(bad).encode()})
  check('Malformed imported feedback cannot replace a valid workspace',memory(imported)==backup['rejections'] and imported.locator('dialog[open]').count()==0)
  # A saved-state adapter verifies migration; native storage is not claimed.
  legacy=dict(backup);legacy.pop('rejections');old=load({'haven.workspace.v1':json.dumps(legacy)})
  check('v1.6 backup migrates without fabricating preferences','Two passes' in old.locator('#preference-panel').inner_text() and len(ids(old))==12)
  denied=load();denied.evaluate("Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:()=>null,setItem:()=>{throw Error('denied')},removeItem:()=>{}}})");passhome(denied,'sample-5');prefs(denied)
  check('Denied persistence is visible in preference panel','Session only' in denied.locator('.preferences-modal').inner_text())
  denied_backup=json.loads(download(denied,'.preferences-modal [data-action="export-backup"]'))
  check('Session-only feedback remains exportable',denied_backup['rejections']['records']['sample-5']['reason']=='HOA too high')
  custom_seed=make_seed("const h={...data[0],id:'custom-test',name:'Custom feedback home',custom:true};w.customProperties=[h];w.rejections=passProperty(w.rejections,h,'Price too high','',null)")
  custom=load(custom_seed);nav(custom,'custom');custom.locator('.property-title').click();custom.locator('[data-action="delete-property"]').click();custom.locator('[data-action="confirm-delete"]').click()
  check('Deleting a custom property also prunes its rejection evidence',store(custom)['customProperties']==[] and memory(custom)['records']=={})
  all_seed=make_seed("for(const h of data)w.rejections=passProperty(w.rejections,h,'Other','Not for me',null)")
  exhausted=load(all_seed);check('All-passed catalogue has a recoverable empty state',exhausted.locator('.property-card').count()==0 and exhausted.locator('[data-action="passes-toggle"]').is_visible())
  reply=send(exhausted,'Show me the cheapest home');check('All-passed assistant directs review instead of making up matches',reply.locator('.assistant-property').count()==0 and 'Your preferences' in reply.inner_text())
  exhausted.locator('.assistant-close').click();exhausted.locator('[data-action="passes-toggle"]').click();check('Show passed recovers browsing even when every home was passed',len(ids(exhausted))==12 and exhausted.locator('#result-summary').inner_text().startswith('60 properties'))
  distance_seed=make_seed("w.living.commute={mode:'simulated',label:'Private work label',city:'Lincoln',state:'NE',anchor:'center',speedMph:25};for(const h of data.filter(p=>p.city==='Lincoln').slice(0,2))w.rejections=passProperty(w.rejections,h,'Too far','',w.living.commute)")
  dist=load(distance_seed);prefs(dist)
  check('Comparable fictional routes activate an explicitly demo-only rule','Shorter demo commutes' in dist.locator('.preference-rule').inner_text() and 'not actual commutes' in dist.locator('.preference-rule').inner_text())
  close(dist);dist.locator('[data-action="workspace"]').click();dist.locator('[data-action="living-work"]').click();dist.locator('#living-work-mode').select_option('remote');dist.locator('#living-work-form button[type="submit"]').click();close(dist);prefs(dist)
  check('Switching work setup suspends incompatible distance evidence without deleting passes',dist.locator('.preference-rule').count()==0 and len(memory(dist)['records'])==2 and '0 of 2' in dist.locator('.preference-pending').inner_text())
  no_route=load();passhome(no_route,'sample-5','Too far');passhome(no_route,'sample-9','Too far');prefs(no_route)
  check('Two unmeasurable Too far passes never invent a distance preference',no_route.locator('.preference-rule').count()==0 and '0 of 2' in no_route.locator('.preference-pending').inner_text())
  # Layout, keyboard and text contrast checks in both whole-app appearances.
  visual=load({'haven.workspace.v1':saved_json})
  for width in [320,390,768,1024,1440]:
   for theme in ['light','dark']:
    visual.set_viewport_size({'width':width,'height':1000});visual.evaluate('(t)=>document.documentElement.dataset.theme=t',theme);nav(visual,'discover')
    check(f'{theme} {width}px discovery has no horizontal overflow',nooverflow(visual));audit(visual,f'{theme} {width}px discover')
    visual.locator('[data-action="layout"][data-layout="list"]').click();check(f'{theme} {width}px list view with feedback actions fits',nooverflow(visual) and visual.locator('.list-layout .pass-button').count()>0);visual.locator('[data-action="layout"][data-layout="grid"]').click()
    prefs(visual);check(f'{theme} {width}px preferences have no horizontal overflow',nooverflow(visual));audit(visual,f'{theme} {width}px preferences')
    visual.locator('.preference-method summary').click();check(f'{theme} {width}px expanded method fits',nooverflow(visual));audit(visual,f'{theme} {width}px method')
    visual.locator('.preference-method summary').click()
    if width==1440:visual.screenshot(path=str(ROOT/f'docs/preferences-{theme}.png'))
    if width==390:visual.screenshot(path=str(ROOT/f'docs/preferences-mobile-{theme}.png'))
    close(visual);search(visual,'sample-1');visual.locator('.property-card [data-action="pass-open"]').click();pick(visual,'Too small')
    check(f'{theme} {width}px reason chips and form fit',nooverflow(visual));audit(visual,f'{theme} {width}px reason picker')
    if width==390:visual.screenshot(path=str(ROOT/f'docs/pass-mobile-{theme}.png'))
    visual.locator('[name="reason"][value="Too small"]').focus();visual.keyboard.press('ArrowRight')
    check(f'{theme} {width}px native radio arrow navigation works',visual.locator('input[name="reason"]:checked').input_value()=='Price too high')
    visual.keyboard.press('Escape');check(f'{theme} {width}px Escape cancels without adding evidence',len(memory(visual)['records'])==2)
  visual.set_viewport_size({'width':390,'height':844});nav(visual,'discover');reply=send(visual,'Use my learned preferences')
  check('Mobile chat with learning disclosure keeps composer in view',visual.locator('#assistant-input').is_visible() and nooverflow(visual));audit(visual,'dark mobile learned assistant');visual.screenshot(path=str(ROOT/'docs/preferences-assistant-mobile.png'))
  visual.locator('.assistant-close').click();prefs(visual)
  check('Reduced motion removes preference-control transitions',visual.locator('#learning-enabled').evaluate('e=>getComputedStyle(e).transitionDuration')=='0s')
  close(visual);visual.emulate_media(reduced_motion='no-preference');search(visual,'sample-1');visual.locator('.property-card [data-action="pass-open"]').click();pick(visual,'HOA too high')
  check('Normal motion retains subtle chip transitions',visual.locator('.pass-chip span').first.evaluate('e=>getComputedStyle(e).transitionDuration')!='0s')
  visual.emulate_media(reduced_motion='reduce');check('Changing reduced-motion preference takes effect immediately',visual.locator('.pass-chip span').first.evaluate('e=>getComputedStyle(e).transitionDuration')=='0s')
  check('No uncaught application exceptions in the tested workflows',not errors)
  fetches=[request for page in pages for request in page.evaluate('window.__fetches||[]')]
  check('New feedback workflows make no fetch or external resource requests',not fetches and not requests)
 finally:
  if checks and not checks[-1]['passed']:
   try:p.screenshot(path=str(ROOT/'docs/rejection-test-failure.png'))
   except Exception:pass
  (ROOT/'docs/rejection-browser-results.json').write_text(json.dumps({'checks':checks,'errors':errors,'requests':requests,'contrast':audits,'storage':'isolated in-memory adapter; not native persistence'},indent=2))
  print(f"\n{sum(c['passed'] for c in checks)} passed; {sum(not c['passed'] for c in checks)} failed",flush=True)
  browser.close()
