import test from 'node:test';
import assert from 'node:assert/strict';
import { parseWorkspace, freshWorkspace, loadWorkspace, saveWorkspace, STORAGE_KEY, validProperty } from '../build/storage.js';
import { defaultAssumptions } from '../build/finance.js';
import { seedProperties } from '../build/data.js';
const fixture=()=>({...seedProperties[0],id:'custom-test',custom:true});
const encode=x=>JSON.stringify(x);
test('workspace backup round-trips',()=>{const w=freshWorkspace();w.customProperties.push(fixture());w.savedIds=['sample-1','custom-test'];w.notes['custom-test']='Check repair costs';w.scenarios.push({id:'s1',name:'Test',propertyId:'custom-test',assumptions:defaultAssumptions(fixture()),savedAt:Date.now()});assert.deepEqual(parseWorkspace(encode(w)),w)});
test('unsupported backup version is rejected',()=>assert.throws(()=>parseWorkspace(encode({...freshWorkspace(),version:2})),/version/));
test('malformed JSON is rejected',()=>assert.throws(()=>parseWorkspace('{nope')));
test('incomplete custom property is rejected',()=>assert.throws(()=>parseWorkspace(encode({...freshWorkspace(),customProperties:[{id:'bad'}]})),/property data/));
test('duplicate custom IDs cannot overwrite one another',()=>assert.throws(()=>parseWorkspace(encode({...freshWorkspace(),customProperties:[fixture(),fixture()]})),/unique/));
test('sample IDs are reserved',()=>assert.throws(()=>parseWorkspace(encode({...freshWorkspace(),customProperties:[seedProperties[0]]})),/reserved/));
test('saved and compared IDs are deduplicated and comparison capped at three',()=>{const w=parseWorkspace(encode({...freshWorkspace(),savedIds:['a','a','b'],compareIds:['a','a','b','c','d']}));assert.deepEqual(w.savedIds,['a','b']);assert.deepEqual(w.compareIds,['a','b','c'])});
test('invalid scenario values are not trusted',()=>{const w=freshWorkspace();w.scenarios.push({id:'s',name:'S',propertyId:'sample-1',savedAt:1,assumptions:{...defaultAssumptions(seedProperties[0]),downPercent:999}});assert.throws(()=>parseWorkspace(encode(w)),/scenarios/)});
test('prototype keys in imported notes are rejected',()=>assert.throws(()=>parseWorkspace('{"version":1,"savedIds":[],"compareIds":[],"customProperties":[],"searches":[],"scenarios":[],"notes":{"__proto__":"bad"}}'),/notes/));
test('oversized backup is rejected before parsing',()=>assert.throws(()=>parseWorkspace(' '.repeat(3_000_001)),/too large/));
test('custom photo URL must be HTTPS or blank',()=>{assert.equal(validProperty({...fixture(),photo:'javascript:alert(1)'}),false);assert.equal(validProperty({...fixture(),photo:''}),true)});
test('local storage round-trip uses the versioned key',()=>{const values=new Map();globalThis.localStorage={setItem:(k,v)=>values.set(k,v),getItem:k=>values.get(k)??null,removeItem:k=>values.delete(k)};const w=freshWorkspace();w.savedIds=['sample-2'];assert.equal(saveWorkspace(w),true);assert.ok(values.has(STORAGE_KEY));assert.deepEqual(loadWorkspace().workspace,w);assert.equal(loadWorkspace().available,true)});
test('unavailable storage falls back to a working session workspace',()=>{Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('Blocked')}});const result=loadWorkspace();assert.equal(result.available,false);assert.deepEqual(result.workspace,freshWorkspace());assert.equal(saveWorkspace(freshWorkspace()),false);delete globalThis.localStorage});
test('corrupt saved state is preserved as a recovery copy',()=>{const values=new Map([[STORAGE_KEY,'broken json']]);globalThis.localStorage={setItem:(k,v)=>values.set(k,v),getItem:k=>values.get(k)??null,removeItem:k=>values.delete(k)};const result=loadWorkspace();assert.equal(result.available,true);assert.equal(values.get(STORAGE_KEY+'.recovery'),'broken json');assert.match(result.notice,/recovery/);delete globalThis.localStorage});
