import type { State, Property, Participant, HouseholdBudget, LifeInputs, DecisionTab } from './types.js';
import { activeParticipant, lifeFor, calculateLife, emptyDecisionHome, assessFit, sharedFit, tourQuestions, stages, stressNames, lifeLimits } from './decision-engine.js';
import { escapeHTML as e, money, number, icon, propertyImage } from './ui.js';
import { propertyPickerView } from './property-picker.js';

const stamp=(text:string,kind='')=>`<span class="decision-stamp ${kind}">${e(text)}</span>`;
const line=(label:string,value:string,cl='')=>`<div class="decision-line ${cl}"><span>${label}</span><strong>${value}</strong></div>`;
const noBudget=()=>`<div class="life-no-budget"><span class="decision-symbol">${icon('leaf')}</span><h2>Make this about your life.</h2><p>Set a household budget to see what’s left after housing, everyday expenses, and your savings goal.</p><button class="btn primary" data-action="decision-budget">Set up my budget ${icon('arrow')}</button><button class="text-button" data-action="decision-example">Explore with a sample budget</button><small>Nothing connects to a bank. Your inputs stay in this browser.</small></div>`;

export function decisionView(s:State,properties:Property[]):string {
  const d=s.workspace.decisions,p=properties.find(p=>p.id===d.currentPropertyId)||properties[0],who=activeParticipant(d);
  const tabs:[DecisionTab,string,string][]=[['life','Your Life Here','leaf'],['together','Together','chat'],['tour','Before You Tour','list']];
  const saved=s.workspace.savedIds.includes(p.id);
  return `<section class="decision-page"><div class="decision-heading"><div><span class="eyebrow">A LITTLE CLARITY FOR YOUR NEXT MOVE</span><h1>Picture your life here<span>.</span></h1><p>The numbers, the people, the questions. One place to decide.</p></div><label class="decision-profile"><span>LOCAL PROFILE</span><select id="decision-person" aria-label="Active participant">${d.participants.map(x=>`<option value="${e(x.id)}" ${x.id===who.id?'selected':''}>${e(x.name)}</option>`).join('')}</select></label></div>
  <div class="decision-home-selector">${propertyPickerView(p).replace('EXPLORING A SCENARIO FOR','YOUR HOME DECISION').replace('Property to analyze','Home to explore')}</div>
  <section class="decision-property" aria-label="Selected home">${propertyImage(p)}<div class="decision-property-copy">${stamp(p.custom?'Your entry · Unverified':'Fictional demo home')}<h2>${e(p.name)}</h2><p>${e(p.city)}, ${e(p.state)} · ${e(p.neighborhood)}</p><div class="decision-specs"><span>${icon('bed')}${p.beds} beds</span><span>${icon('area')}${number(p.sqft)} sq ft</span><span>${e(p.type)}</span></div></div><div class="decision-property-side"><strong>${money(p.price)}</strong><span>Asking price · ${p.custom?'user-entered':'demo data'}</span><div><button class="btn small ${saved?'is-on':''}" data-action="save-toggle" data-id="${e(p.id)}" aria-pressed="${saved}">${icon('heart')}${saved?'Saved':'Save home'}</button><button class="text-button" data-action="details" data-id="${e(p.id)}">Listing ${icon('diagonal')}</button></div></div></section>
  ${p.type==='Duplex'?`<p class="decision-disclosure">${icon('info')}Duplex bedrooms and area are combined totals. This planner covers the whole purchase; it does not assume rental income or a per-unit layout.</p>`:''}
  <div class="decision-tabs" role="tablist" aria-label="Home decision tools">${tabs.map(([key,label,symbol],i)=>`<button id="decision-tab-${key}" role="tab" aria-selected="${s.decisionTab===key}" aria-controls="decision-panel" tabindex="${s.decisionTab===key?'0':'-1'}" data-action="decision-tab" data-tab="${key}"><span class="decision-tab-number">0${i+1}</span>${icon(symbol)}${label}</button>`).join('')}</div>
  <section id="decision-panel" role="tabpanel" aria-labelledby="decision-tab-${s.decisionTab}">${s.decisionTab==='life'?lifeView(s,p,who,properties):s.decisionTab==='together'?togetherView(s,p,who,properties):tourView(s,p,who)}</section>
  <p class="decision-bottom-note">${icon('info')}Fictional listings. Educational estimates, not financial advice. Saved locally; profiles are not secure accounts or live collaboration.</p></section>`;
}
export function budgetForm(who:Participant):string {
 const b=who.budget;
 const fields:[keyof HouseholdBudget,string,string][]=[['income','Monthly take-home income','After taxes; the amount available to your household.'],['expenses','Other monthly expenses','Exclude housing, savings, and this home’s utilities to avoid double counting.'],['savings','Monthly savings goal','The amount you want to set aside each month.'],['cash','Cash available for this move','The total cash you want to include before upfront purchase costs.'],['cushion','Monthly breathing-room target','A comparison target, not another expense.']];
 return `<form id="decision-budget-form"><div class="modal-heading"><span class="eyebrow">YOUR LIFE, YOUR NUMBERS</span><h2 id="dialog-title">${e(who.name)}’s household plan.</h2><p>Set this once, then compare homes with the same budget. All amounts are in US dollars.</p></div>${b?.example?'<p class="notice warning">You are editing sample values. Only save them as your own after replacing them.</p>':''}<div class="decision-form-grid">${fields.map(([key,label,hint])=>`<label class="form-field ${key==='cushion'?'full':''}"><span>${label}</span><div class="decision-money-field"><span>$</span><input type="number" name="${key}" min="0" max="${key==='cash'?1000000000:1000000}" step="0.01" required inputmode="decimal" value="${b?b[key]:''}"></div><small>${hint}</small></label>`).join('')}</div><label class="decision-checkbox"><input name="example" type="checkbox" ${b?.example?'checked':''}><span>These are sample figures, not my personal finances.</span></label><p class="decision-disclosure">Not shown in Together by default. Stored on this device and included in full workspace backups. Anyone with access to this browser can switch profiles.</p><p class="decision-error" id="decision-form-error" role="alert"></p><div class="modal-actions"><button class="btn" type="button" data-action="close-dialog">Cancel</button><button class="btn primary" type="submit">Save household plan ${icon('check')}</button></div></form>`;
}
const lifeLabels:Record<keyof LifeInputs,string>={downPercent:'Down payment (%)',interestRate:'Sample interest rate (%)',years:'Loan term (years)',closingPercent:'Closing costs (%)',taxAnnual:'Property tax ($ / year)',insuranceMonthly:'Insurance ($ / month)',hoaMonthly:'Association fees ($ / month)',mortgageInsurance:'Mortgage insurance ($ / month)',utilities:'Utilities ($ / month)',maintenance:'Maintenance reserve ($ / month)',moving:'Moving costs ($)',repairs:'Initial repairs ($)'};
function lifeField(key:keyof LifeInputs,a:LifeInputs,source:string):string {
 return `<label class="form-field"><span>${lifeLabels[key]}</span><input id="life-${key}" name="${key}" data-life="${key}" type="number" required min="${lifeLimits[key][0]}" max="${lifeLimits[key][1]}" step="${key==='years'?1:0.01}" inputmode="decimal" value="${a[key]}"><small>${source}</small></label>`;
}
function lifeView(s:State,p:Property,who:Participant,properties:Property[]):string {
 const a=lifeFor(p,who),b=who.budget,d=s.workspace.decisions;
 const customized=!!who.life[p.id];
 const source=(field:keyof LifeInputs)=>customized?'Your saved scenario input':['taxAnnual','insuranceMonthly','hoaMonthly'].includes(field)?(p.custom?'User-entered property input':'Fictional listing input'):field==='maintenance'?'Sample: 1% of price / 12, rounded':field==='interestRate'?'Illustrative assumption; not a rate quote':field==='mortgageInsurance'?'Starts at $0; add a quote if applicable':'Editable sample assumption';
 return `<div class="decision-section-heading"><div><h2>A home that leaves room for living.</h2><p>See the whole month, not just the mortgage.</p></div>${b?`<button class="btn small" data-action="decision-budget">${icon('sliders')}Edit household plan</button>`:''}</div>
 <div class="life-grid"><div class="life-inputs">${b?`<section class="decision-card household-card"><div class="decision-card-heading"><h3>${e(who.name)}’s household plan</h3>${stamp(b.example?'Sample budget':'Your inputs')}</div><div class="household-values"><div><span>Take-home / month</span><strong>${money(b.income)}</strong></div><div><span>Other expenses / month</span><strong>${money(b.expenses)}</strong></div><div><span>Savings goal / month</span><strong>${money(b.savings)}</strong></div><div><span>Cash for your move</span><strong>${money(b.cash)}</strong></div></div><p class="decision-micro">${icon('info')}Budget details aren’t shown in Together. Local profiles are not private accounts.</p></section>`:''}
 <section class="decision-card"><div class="decision-card-heading"><div><h3>Make the assumptions yours.</h3><p>Saved for this home and this profile.</p></div><button class="text-button" data-action="decision-reset-inputs">Reset</button></div><form id="decision-life-form" novalidate><details class="decision-accordion" open><summary>Purchase & financing ${icon('down')}</summary><div class="decision-form-grid">${(['downPercent','interestRate','years','closingPercent'] as (keyof LifeInputs)[]).map(k=>lifeField(k,a,source(k))).join('')}</div></details><details class="decision-accordion"><summary>Monthly ownership costs ${icon('down')}</summary><div class="decision-form-grid">${(['taxAnnual','insuranceMonthly','hoaMonthly','mortgageInsurance','utilities','maintenance'] as (keyof LifeInputs)[]).map(k=>lifeField(k,a,source(k))).join('')}</div></details><details class="decision-accordion"><summary>Moving & initial repairs ${icon('down')}</summary><div class="decision-form-grid">${(['moving','repairs'] as (keyof LifeInputs)[]).map(k=>lifeField(k,a,source(k))).join('')}</div></details><p id="decision-life-error" class="decision-error" role="alert" hidden></p><p class="decision-micro">Valid changes save automatically. Estimated costs are not verified bills.</p></form></section>
 <section class="decision-card stress-card"><div class="decision-card-heading"><div><h3>Make room for a what-if.</h3><p>Test one change at a time against the same plan.</p></div>${icon('sliders')}</div><div class="stress-tabs" role="group" aria-label="Budget stress scenario">${(['baseline','income','expenses','repair'] as const).map(k=>`<button data-action="decision-stress" data-kind="${k}" aria-pressed="${s.decisionStress===k}">${k==='baseline'?'Everyday':k==='income'?'Income drop':k==='expenses'?'Higher expenses':'A repair'}</button>`).join('')}</div>${s.decisionStress==='baseline'?'<p class="decision-micro">Your entered income and costs, with no additional shock.</p>':`<label class="form-field stress-value"><span>${s.decisionStress==='income'?'Take-home income decrease (%)':s.decisionStress==='expenses'?'Additional non-housing expenses ($ / month)':'One-time repair paid from remaining cash ($)'}</span><input id="decision-stress-value" type="number" min="0" max="${s.decisionStress==='income'?100:s.decisionStress==='expenses'?1000000:100000000}" step="0.01" value="${s.decisionStress==='income'?d.stressInputs.incomeDrop:s.decisionStress==='expenses'?d.stressInputs.expenseIncrease:d.stressInputs.repairCost}"></label>`}<p class="decision-micro">A one-time repair changes cash remaining, not your recurring monthly expenses.</p></section></div>
 <div id="decision-life-results" class="life-results" aria-live="polite" aria-atomic="false">${lifeResults(s,p,who)}</div></div>
 ${b?`<section class="decision-card life-compare"><div class="decision-card-heading"><div><h3>Your shortlist, one household plan.</h3><p>Baseline comparison of ${s.workspace.savedIds.length} saved home${s.workspace.savedIds.length===1?'':'s'}, using this profile’s assumptions. Ordered by monthly money remaining.</p></div></div>${s.workspace.savedIds.length?`<div class="decision-table-wrap"><table><thead><tr><th>Home</th><th>Housing / mo</th><th>Left / mo</th><th>Cash remaining</th><th><span class="sr-only">Open</span></th></tr></thead><tbody>${properties.filter(x=>s.workspace.savedIds.includes(x.id)).map(x=>({p:x,m:calculateLife(x.price,b,lifeFor(x,who))})).sort((a,b)=>b.m.leftover-a.m.leftover).map(({p:x,m})=>`<tr><td><strong>${e(x.name)}</strong><small>${e(x.city)} · ${money(x.price)}</small></td><td>${money(m.housing)}</td><td class="${m.leftover<0?'decision-negative':''}">${money(m.leftover)}</td><td class="${m.cashRemaining<0?'decision-negative':''}">${money(m.cashRemaining)}</td><td><button class="text-button" data-action="decision-open" data-id="${e(x.id)}">Explore ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="decision-empty-copy">Save a few homes to see them here. Your budget follows you across the entire collection.</p>'}</section>${snapshotsView(s,who)}`:''}`;
}
export function lifeResults(s:State,p:Property,who:Participant):string {
 if(!who.budget)return noBudget();
 const b=who.budget,a=lifeFor(p,who),m=calculateLife(p.price,b,a,s.decisionStress,s.workspace.decisions.stressInputs);
 const costRows:[string,number][]=[['Mortgage principal & interest',m.mortgage],['Property tax',m.tax],['Home insurance',m.insurance],['Association fees',m.hoa],['Mortgage insurance',m.pmi],['Utilities',m.utilities],['Maintenance reserve',m.maintenance]];
 return `<section class="life-outcome"><div class="life-outcome-top"><span>${e(stressNames[s.decisionStress])}</span>${stamp(b.example?'Sample budget':'Your inputs')}</div><span class="life-outcome-label">After housing, expenses & savings</span><strong id="life-leftover">${money(m.leftover)}<small>/ month</small></strong><p>${m.leftover<0?'Your modeled spending exceeds your take-home income.':'A little breathing room, made visible.'}</p><div class="life-cushion">${icon(m.cushionGap>=0?'check':'info')}<span>${money(Math.abs(m.cushionGap))} ${m.cushionGap>=0?'above':'below'} your ${money(b.cushion)} monthly cushion target.</span></div></section>
 <section class="decision-card life-breakdown"><div class="decision-card-heading"><h3>Your month, at a glance.</h3>${stamp('Estimate')}</div>${line('Take-home income',money(m.income))}${line('Total housing costs',money(m.housing))}${line('Other living expenses',money(m.expenses))}${line('Savings goal',money(m.savings))}${line('Left for you',money(m.leftover),'decision-line-total')}<details class="decision-accordion"><summary>What’s inside housing costs ${icon('down')}</summary><div class="housing-items">${costRows.map(([label,v])=>line(e(label),money(v))).join('')}</div></details>${a.downPercent<20&&m.pmi===0?`<p class="decision-disclosure">${icon('info')}Mortgage insurance is $0 in this estimate. With less than 20% down, a lender may require it; enter a quote if applicable. This is not loan approval.</p>`:''}</section>
 <section class="decision-card move-card"><div class="decision-card-heading"><h3>Before you get the keys.</h3>${icon('home')}</div>${line('Down payment',money(m.down))}${line('Estimated closing costs',money(m.closing))}${line('Moving + initial repairs',money(m.moving+m.initialRepairs))}${line('Total upfront',money(m.upfront),'decision-line-total')}${m.repairStress?line('Additional repair shock',money(m.repairStress)):''}<div class="cash-remainder ${m.cashRemaining<0?'has-shortfall':''}"><span>${m.cashRemaining<0?'Additional cash needed':'Cash left after your move'}${m.repairStress?' & repair':''}</span><strong id="life-cash">${money(Math.abs(m.cashRemaining))}</strong></div><p class="decision-micro">${m.cashRemaining<0?'Your entered available cash does not cover this scenario. No borrowing to cover the gap is assumed.':'Based on the cash amount you entered, not a bank balance or a lender determination.'}</p></section>
 <div class="decision-result-actions"><button class="btn primary" data-action="decision-save-snapshot">Save this scenario ${icon('plus')}</button><button class="btn" data-action="decision-export-life" aria-label="Export life scenario">${icon('download')}Export</button></div><p class="decision-micro">Snapshot exports contain budget details. They are separate from the shareable tour brief.</p>`;
}
function snapshotsView(s:State,who:Participant):string {
 const items=s.workspace.decisions.snapshots.filter(x=>x.participantId===who.id);
 return `<section class="decision-card life-snapshots"><div class="decision-card-heading"><div><h3>Perspectives worth keeping.</h3><p>Private to this profile’s view. Snapshots preserve price, budget, and every assumption.</p></div>${stamp(`${items.length} saved`)}</div>${items.length?`<div class="snapshot-list">${items.map(x=>{const m=calculateLife(x.price,x.budget,x.inputs,x.stress,x.stressInputs);return `<article><span>${icon('folder')}</span><div><strong>${e(x.name)}</strong><p>${money(m.leftover)} left / month · ${e(stressNames[x.stress])} · Price snapshot ${money(x.price)}</p></div><button class="text-button" data-action="decision-load-snapshot" data-id="${e(x.id)}">Load</button><button class="icon-button" data-action="decision-delete-snapshot" data-id="${e(x.id)}" aria-label="Delete ${e(x.name)}">${icon('x')}</button></article>`;}).join('')}</div>`:'<p class="decision-empty-copy">Save a scenario to return to the same numbers later.</p>'}</section>`;
}
export function participantForm(person?:Participant,cities:string[]=[]):string {
 const w=person,req=w?.priorities;
 return `<form id="decision-participant-form" data-id="${e(w?.id||'')}"><div class="modal-heading"><span class="eyebrow">GOOD DECISIONS START WITH LISTENING</span><h2 id="dialog-title">${w?'Edit priorities.':'Make room for someone.'}</h2><p>A local demo profile—not an account or invitation. These stated priorities will be visible in Together.</p></div><label class="form-field"><span>Name</span><input name="name" required maxlength="40" value="${e(w?.name||'')}" placeholder="e.g. Alex"></label><div class="decision-form-grid"><label class="form-field"><span>City (optional)</span><input name="city" list="decision-cities" maxlength="100" value="${e(req?.city||'')}" placeholder="Any city"><datalist id="decision-cities">${cities.map(city=>`<option value="${e(city)}"></option>`).join('')}</datalist></label><label class="form-field"><span>Property type</span><select name="type">${['','Single-family','Condo','Townhouse','Duplex'].map(t=>`<option value="${t}" ${req?.type===t?'selected':''}>${t||'Any type'}</option>`).join('')}</select></label><label class="form-field"><span>Maximum purchase price ($)</span><input name="maxPrice" type="number" min="0" max="100000000" step="1" value="${req?.maxPrice||''}" placeholder="No limit"></label><label class="form-field"><span>Minimum bedrooms</span><input name="minBeds" type="number" min="0" max="100" step="1" value="${req?.minBeds||''}" placeholder="Any"></label><label class="form-field"><span>Minimum floor area (sq ft)</span><input name="minSqft" type="number" min="0" max="1000000" step="1" value="${req?.minSqft||''}" placeholder="Any"></label></div><div class="decision-check-row"><label class="decision-checkbox"><input name="outdoor" type="checkbox" ${req?.outdoor?'checked':''}>Outdoor space</label><label class="decision-checkbox"><input name="light" type="checkbox" ${req?.light?'checked':''}>Natural light</label></div><label class="form-field"><span>Other priorities to discuss</span><textarea name="notes" rows="2" maxlength="2000" placeholder="These are kept as discussion points, not automatically inferred.">${e(req?.notes||'')}</textarea></label><p class="decision-error" id="decision-form-error" role="alert"></p><div class="modal-actions"><button type="button" class="btn" data-action="close-dialog">Cancel</button><button type="submit" class="btn primary">${w?'Save priorities':'Add participant'} ${icon('check')}</button></div></form>`;
}
function togetherView(s:State,p:Property,who:Participant,properties:Property[]):string {
 const d=s.workspace.decisions,home=d.homes[p.id]||emptyDecisionHome(),fit=sharedFit(p,d.participants),review=home.reviews[who.id];
 const saved=properties.filter(x=>s.workspace.savedIds.includes(x.id));
 return `<div class="decision-section-heading"><div><h2>A home you can get behind. Together.</h2><p>Make space for each person’s priorities, without losing your own.</p></div><button class="btn" data-action="decision-add-person" ${d.participants.length>=8?'disabled':''}>${icon('plus')}Add participant</button></div><div class="decision-local-notice">${icon('info')}<p><strong>Local collaboration demo.</strong> Switch profiles to try different perspectives on this device. No invitations, accounts, or cross-device sync. Anyone using this browser can access all profiles.</p></div>
 <div class="together-summary"><div><span class="eyebrow">WHERE YOU STAND</span><h3>${fit.status}</h3><p>${e(fit.detail)}</p></div><label class="form-field"><span>This home’s shared stage</span><select id="decision-stage">${stages.map(stage=>`<option ${home.stage===stage?'selected':''}>${stage}</option>`).join('')}</select></label></div>
 <div class="participant-grid">${d.participants.map(person=>{const points=assessFit(p,person.priorities),r=home.reviews[person.id],shared=person.shareBudget&&person.budget?calculateLife(p.price,person.budget,lifeFor(p,person)):null;return `<article class="decision-card participant-card" data-person-card="${e(person.id)}"><div class="person-heading"><span class="person-avatar">${e(person.name.slice(0,1).toUpperCase())}</span><div><h3>${e(person.name)}</h3><small>${person.id===who.id?'Active local profile':'Local participant'}</small></div><button class="icon-button" data-action="decision-edit-person" data-id="${e(person.id)}" aria-label="Edit ${e(person.name)}’s priorities">${icon('sliders')}</button></div><div class="person-fit">${points.length?points.map(point=>`<div class="fit-point ${point.status}">${icon(point.status==='fits'?'check':'info')}<p><strong>${e(point.label)}</strong><span>${e(point.detail)}</span></p></div>`).join(''):'<p class="decision-empty-copy">No priorities yet. Add must-haves to make this comparison meaningful.</p>'}</div>${r?`<div class="person-review">${stamp(r.stance)}<p>${e(r.note||'No note added.')}</p></div>`:'<p class="decision-micro">No opinion recorded for this home yet.</p>'}${shared?`<div class="shared-budget-summary"><span>Explicitly shared budget summary${person.budget?.example?' · sample budget':''}</span><strong>${money(shared.leftover)} left / month</strong><small>Baseline, after this profile’s housing, expenses, and savings. Raw budget inputs are not shown here.</small></div>`:'<p class="decision-private">Budget not shared in this view.</p>'}${d.participants.length>1?`<button class="text-button decision-remove-person" data-action="decision-remove-person" data-id="${e(person.id)}">Remove profile</button>`:''}</article>`;}).join('')}</div>
 <div class="together-work"><section class="decision-card"><div class="decision-card-heading"><div><h3>${e(who.name)}’s take.</h3><p>Your note is visible to everyone in this local workspace.</p></div></div><form id="decision-review-form"><fieldset class="opinion-options"><legend class="sr-only">Your opinion of this home</legend>${['Interested','Unsure','Not for me'].map((stance,i)=>`<label><input type="radio" name="stance" value="${stance}" ${(review?.stance===stance||!review&&i===1)?'checked':''}><span>${stance}</span></label>`).join('')}</fieldset><label class="form-field"><span>What’s on your mind?</span><textarea name="note" maxlength="3000" rows="3" placeholder="What works? What would you want to know?">${e(review?.note||'')}</textarea></label><div class="decision-inline-actions"><button class="btn primary" type="submit">Save my take ${icon('check')}</button>${review?'<button type="button" class="text-button" data-action="decision-clear-review">Remove my take</button>':''}</div></form></section><section class="decision-card privacy-card"><span class="decision-symbol">${icon('home')}</span><h3>Your numbers. Your choice.</h3><p>Raw income, expenses, and savings are not displayed in Together. You can choose to show only your calculated monthly amount remaining.</p><label class="decision-checkbox"><input id="decision-share-budget" type="checkbox" ${who.shareBudget?'checked':''} ${!who.budget?'disabled':''}><span>Share my calculated budget summary here</span></label>${!who.budget?'<button class="text-button" data-action="decision-budget">Set up a budget first</button>':''}<p class="decision-micro">This controls presentation, not security. Profiles share one browser, and full backups include all budgets.</p></section></div>
 <section class="decision-card together-shortlist"><div class="decision-card-heading"><div><h3>A shared shortlist, not a shared guess.</h3><p>All saved homes, compared against every participant’s recorded priorities.</p></div>${stamp(`${saved.length} saved`)}</div>${saved.length?`<div class="decision-table-wrap"><table><thead><tr><th>Home</th><th>Common fit</th><th>Stage</th><th></th></tr></thead><tbody>${saved.map(x=>{const common=sharedFit(x,d.participants);return `<tr><td><strong>${e(x.name)}</strong><small>${e(x.city)} · ${money(x.price)}</small></td><td>${e(common.status)}<small>${e(common.detail)}</small></td><td>${e(d.homes[x.id]?.stage||'Considering')}</td><td><button class="text-button" data-action="decision-open" data-id="${e(x.id)}">Explore ${icon('arrow')}</button></td></tr>`;}).join('')}</tbody></table></div>`:'<p class="decision-empty-copy">Save homes from Discover or the property header to build your shared shortlist.</p>'}</section>`;
}
function tourView(s:State,p:Property,who:Participant):string {
 const home=s.workspace.decisions.homes[p.id]||emptyDecisionHome(),questions=tourQuestions(p,who.priorities,home),done=questions.filter(q=>q.resolved).length;
 const fit=assessFit(p,who.priorities),fits=fit.filter(x=>x.status==='fits'),tradeoffs=fit.filter(x=>x.status==='tradeoff'),unknown=fit.filter(x=>x.status==='unknown');
 return `<div class="decision-section-heading"><div><h2>Walk in with better questions.</h2><p>A decision brief for ${e(who.name)}. Based on recorded facts, not an inspection.</p></div><button class="btn" data-action="decision-export-tour">${icon('download')}Export tour brief</button></div><div class="tour-brief-grid"><section class="decision-card"><span class="eyebrow">01 / WHY IT FITS</span><h3>Start with what you know.</h3>${fits.length?fits.map(x=>`<p class="brief-point">${icon('check')}<span>${e(x.detail)}</span></p>`).join(''):`<p class="brief-point">${icon('home')}<span>${money(p.price)} · ${e(p.city)}, ${e(p.state)} · ${p.beds} beds · ${number(p.sqft)} sq ft${p.type==='Duplex'?' (combined)':''}.</span></p><p class="decision-micro">Add your priorities in Together to check personal fit.</p>`}<small class="brief-source">Source: ${p.custom?'your unverified entry':'fictional listing data'}</small></section><section class="decision-card"><span class="eyebrow">02 / THE TRADE-OFFS</span><h3>Be honest about the gaps.</h3>${tradeoffs.length?tradeoffs.map(x=>`<p class="brief-point">${icon('info')}<span>${e(x.detail)}</span></p>`).join(''):'<p class="decision-empty-copy">No conflicts found against your entered numerical requirements. This does not mean the home has no drawbacks.</p>'}</section><section class="decision-card"><span class="eyebrow">03 / STILL UNKNOWN</span><h3>Don’t fill in the blanks.</h3>${unknown.map(x=>`<p class="brief-point">${icon('help')}<span>${e(x.detail)}</span></p>`).join('')}<p class="decision-empty-copy">Roof age, system condition, inspection findings, and actual utility bills are not provided. Answers below are user-recorded—not independently verified.</p></section></div>
 <div class="tour-grid"><section class="decision-card tour-checklist"><div class="decision-card-heading"><div><h3>Take these questions with you.</h3><p>${done} of ${questions.length} questions have recorded answers and sources.</p></div>${stamp(`${done}/${questions.length}`)}</div><progress class="tour-progress" value="${done}" max="${questions.length}" aria-label="Questions with recorded answers">${done}/${questions.length}</progress><div class="tour-question-list">${questions.map(q=>`<button class="tour-question ${q.resolved?'resolved':''}" data-action="decision-question" data-id="${e(q.id)}"><span class="question-check">${q.resolved?icon('check'):icon('plus')}</span><span><strong>${e(q.text)}</strong>${q.answer?`<small>${e(q.answer.slice(0,180))}${q.answer.length>180?'…':''}</small>`:''}<em>${q.resolved?'Recorded answer':'Needs an answer'}${q.source?` · ${e(q.source)}`:''}</em></span>${icon('chevron')}</button>`).join('')}</div><form id="decision-question-add" class="tour-add-question"><label class="form-field"><span>Something else on your mind?</span><input name="question" required maxlength="500" placeholder="Add your own question…"></label><button class="btn small" type="submit">${icon('plus')}Add question</button></form><p class="decision-micro">Recording an answer is not a professional verification or inspection.</p></section>
 <section class="decision-card tour-notes"><div class="decision-card-heading"><div><h3>Leave a little room for notes.</h3><p>Shared locally with all participants.</p></div>${icon('list')}</div><form id="decision-visit-form"><label class="form-field"><span>Planned visit (optional)</span><input name="date" type="datetime-local" value="${e(home.visit.date)}"><small>A local planning note, not a calendar event or appointment booking.</small></label><label class="form-field"><span>Tour notes</span><textarea name="notes" maxlength="5000" rows="7" placeholder="What did you notice? Which answers need following up?">${e(home.visit.notes)}</textarea></label>${home.visit.author?`<p class="decision-micro">Last edited by ${e(s.workspace.decisions.participants.find(x=>x.id===home.visit.author)?.name||'a local participant')}.</p>`:''}<button class="btn primary" type="submit">Save visit notes ${icon('check')}</button></form><div class="tour-note-tip"><span class="eyebrow">GOOD TO KNOW</span><p>The brief export includes property facts, priorities, tour notes, questions, and recorded sources. It never includes household budgets.</p></div></section></div>`;
}
