import type { Property } from './types.js';
import { negotiationReport, displayDate, COMPARABLE_POLICY } from './negotiation-engine.js';
import { escapeHTML as e, money, number, icon } from './ui.js';

const dollarsPerFoot=(n:number):string=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);

/** Native details keeps collapse, keyboard behavior and focus independent of app state. */
export function negotiationSection(p:Property):string {
  const r=negotiationReport(p),h=r.history,c=r.comparison;
  const summary=`<summary class="negotiation-toggle"><span class="negotiation-title"><span class="negotiation-title-line">${icon('compare')}<strong>Negotiation context</strong></span><span>${r.status==='no-fixture'?'No sample history attached':'Asking-price history & comparable sales'}</span></span><span class="negotiation-badge">${r.status==='no-fixture'?'No data':'Fictional'}</span>${icon('down','negotiation-chevron')}</summary>`;
  if(r.status==='no-fixture')return `<details class="negotiation-panel" id="negotiation-panel">${summary}<div class="negotiation-body"><div class="negotiation-empty"><h3>No history is better than invented history.</h3><p>This property has no attached sample asking-price history or sold comparisons. Haven does not infer sales, days on market or a price advantage from your address or calculator inputs.</p><p>Demo sales belong only to the original 60 fictional listings. No market data has been looked up.</p></div></div></details>`;
  const history=h ? `<div class="negotiation-history"><div class="negotiation-section-heading"><h4>Asking-price history</h4><span>${h.dropCount ? `${h.dropCount} recorded ${h.dropCount===1?'reduction':'reductions'}`:'No recorded reductions'}</span></div><ol class="negotiation-timeline">${h.events.map((event,index)=>`<li><div><strong>${index===0?'Originally listed':event.change<0?'Price reduced':event.change>0?'Price increased':'Price unchanged'}</strong><time datetime="${e(event.date)}">${displayDate(event.date)}</time></div><div class="negotiation-history-value"><strong>${money(event.price)}</strong>${index===0?'<span>Original asking price</span>':`<span>${event.change<0?'Down':event.change>0?'Up':'Change'} ${money(Math.abs(event.change))} · ${Math.abs(event.changePercent).toFixed(1)}%</span>`}</div></li>`).join('')}</ol><p class="negotiation-note">${h.dropCount?'Reductions compare each recorded asking price with the previous one.':'The sample asking price has not been reduced in this listing period.'} Days on market measure this one listing period, not cumulative exposure or seller urgency.</p></div>` : '<div class="negotiation-empty"><h4>Asking-price history unavailable</h4><p>The attached history does not match this listing’s current details. No dates, cuts or days on market are inferred.</p></div>';
  const comps=r.sales.map((sale,index)=>`<li class="negotiation-comp" data-comp-id="${e(sale.id)}"><div class="negotiation-comp-identity"><span class="negotiation-comp-number" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><div><strong>${e(sale.address)}</strong><span>${e(sale.type)} · ${sale.beds} beds · ${number(sale.sqft)} sq ft</span><span>${e(sale.neighborhood)} · ${e(sale.city)}, ${e(sale.state)}</span></div></div><div class="negotiation-comp-sale"><strong>${money(sale.price)}</strong><span>${dollarsPerFoot(sale.price/sale.sqft)}/sq ft</span><span>Sold <time datetime="${e(sale.soldOn)}">${displayDate(sale.soldOn)}</time></span></div></li>`).join('');
  const method=`<details class="negotiation-method"><summary>How this comparison is calculated ${icon('down')}</summary><div><p>Start with the separate fictional sold records. Match this home’s city, state, neighborhood label and property type; keep sales within ±${COMPARABLE_POLICY.maxSizeDifference*100}% of its size and ±${COMPARABLE_POLICY.maxBedroomDifference} bedroom, sold in the ${COMPARABLE_POLICY.maxAgeDays} days ending ${displayDate(r.snapshot)}.</p><p>Choose up to ${COMPARABLE_POLICY.maxCount} closest by size; break ties by most recent sale, then sale ID. Display them newest first. One address counts once. A minimum of ${COMPARABLE_POLICY.minCount} matches is required; the criteria are never widened just to produce a result. Asking price is not a selection filter.</p><p><strong>Formula</strong></p><div class="negotiation-formula">((asking price ÷ home’s sq ft) ÷ median(each sold price ÷ that sale’s sq ft) − 1) × 100</div>${c?`<p class="negotiation-formula-values">Asking: ${money(p.price)} ÷ ${number(p.sqft)} = <strong>${dollarsPerFoot(c.askingPerSqft)}/sq ft</strong>.<br>Median of ${c.count} individual sale ratios: <strong>${dollarsPerFoot(c.medianSoldPerSqft)}/sq ft</strong>.<br>Percentage uses unrounded ratios; display is rounded to one decimal place.</p>`:''}<p>Sold prices are fixed sample records, not generated from this home’s current asking price or your calculator edits. “Nearby” means matching <em>fictional neighborhood labels</em>, not measured proximity. No coordinates or distance checks are used.</p><p>Size-only context: no adjustments for condition, renovation, lot size, age, exact bedroom differences, concessions or sale timing. This is not an appraisal, an offer recommendation, evidence of seller motivation, or a prediction of a negotiated price.</p></div></details>`;
  return `<details class="negotiation-panel" id="negotiation-panel">${summary}<div class="negotiation-body"><p class="negotiation-disclosure">Invented history and sold examples. Fixed demo snapshot: <time datetime="${e(r.snapshot)}">${displayDate(r.snapshot)}</time>. Not current market evidence.</p><div class="negotiation-stats"><div><span>Current asking price</span><strong>${money(p.price)}</strong><small>Listing price, not a scenario</small></div><div><span>Days on market</span><strong>${h?`${h.daysOnMarket} <span>days</span>`:'Unavailable'}</strong><small>${h?`Listed ${displayDate(h.listedOn)}`:'No consistent history'}</small></div><div><span>Recorded reductions</span><strong>${h?(h.dropCount?String(h.dropCount):'None'):'Unavailable'}</strong><small>${h&&h.dropCount?`${money(h.totalReductions)} in total cuts`:h?'In this sample listing period':'No cuts inferred'}</small></div></div>${history}<div class="negotiation-sales"><div class="negotiation-section-heading"><h4>Comparable fictional sales</h4><span>${r.sales.length} ${r.sales.length===1?'match':'matches'} · newest first</span></div><p class="negotiation-note">Same fictional neighborhood & property type · similar size. ${p.type==='Duplex'?'Duplex prices, areas and bedrooms cover both units of the whole building.':'These sold examples are separate from the 60 active demo listings.'}</p>${comps?`<ol class="negotiation-comp-list">${comps}</ol>`:'<p class="negotiation-empty">No eligible sold examples. Haven has not substituted less-comparable homes.</p>'}</div>${method}<div class="negotiation-takeaway" data-comparison-direction="${c?c.direction:'unavailable'}"><span class="eyebrow">THE SAMPLE TAKEAWAY</span><p>${e(r.takeaway)}</p><small>${c?`${c.count} fictional sales · size-only comparison, not a valuation or suggested offer.`:'Fewer than three usable matches: no percentage or price verdict is shown.'}</small></div></div></details>`;
}
